### ISSUE TITLE
Text inputs with no content in them cause a panic when double clicked

### ISSUE THREAD

**Issue by ZakisM** [iced-rs/iced#1041]
@hecrj - Have noticed this issue just now, when running the todos example on MacOS 11.5.2 (With discrete GPU - AMD Radeon Pro 5500M), haven't tested on other platforms:

`cargo run --package todos`

Double click the text input when there is no content inside of it - application crashes

Caused by this line (`native/src/widget/text_input/value.rs:59:28`) where the index is 1 for some reason.

```let next_string = &self.graphemes[index..].concat();```

```thread 'main' panicked at 'range start index 1 out of range for slice of length 0', native/src/widget/text_input_shared/value.rs:59:28
thread 'main' panicked at 'range start index 1 out of range for slice of length 0', native/src/widget/text_input/value.rs:59:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Texture[1] does not exist', /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.10.1/src/hub.rs:129:32
stack backtrace:
   0:        0x103367c14 - std::backtrace_rs::backtrace::libunwind::trace::hd9b9204470182ffc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x103367c14 - std::backtrace_rs::backtrace::trace_unsynchronized::hdc48b9180be04761
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x103367c14 - std::sys_common::backtrace::_print_fmt::h8824de041faf4112
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x103367c14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d168763f08a78b9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x103385b1c - core::fmt::write::h0fa46d4891ed63f1
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:        0x103364bfa - std::io::Write::write_fmt::hacbf9e10e17149ce
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:        0x103369a3f - std::sys_common::backtrace::_print::h26213154a400cfbe
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x103369a3f - std::sys_common::backtrace::print::h0f4ab60f53d1f93b
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x103369a3f - std::panicking::default_hook::{{closure}}::hee7cf38dedfa76fc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:        0x10336953d - std::panicking::default_hook::hd12252412832a45f
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:        0x10336a140 - std::panicking::rust_panic_with_hook::h521fd09e07057893
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:        0x103369be5 - std::panicking::begin_panic_handler::{{closure}}::h3588a5a9cca9e8e5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:        0x1033680b8 - std::sys_common::backtrace::__rust_end_short_backtrace::h86522c151a195ff9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x103369b4a - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:        0x10339e8bb - std::panicking::begin_panic_fmt::hf4ebaa1b90291b0b
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  15:        0x102e97f76 - wgpu_core::hub::Storage<T,I>::get::h2abf75a4cf1cfb79
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.10.1/src/hub.rs:129:32
  16:        0x102d29459 - <wgpu_core::hub::Storage<T,I> as core::ops::index::Index<wgpu_core::id::Valid<I>>>::index::hf88afe6f1964111b
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.10.1/src/hub.rs:102:9
  17:        0x102d2fe71 - wgpu_core::hub::Hub<A,F>::clear::h7ba9b4a29e557d7d
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.10.1/src/hub.rs:651:43
  18:        0x102d2ae9b - <wgpu_core::hub::Global<G> as core::ops::drop::Drop>::drop::h0feb68b10545cefe
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.10.1/src/hub.rs:922:13
  19:        0x102dc2395 - core::ptr::drop_in_place<wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>::h16d9cda6fd3cdea8
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  20:        0x102dbd7c0 - core::ptr::drop_in_place<wgpu::backend::direct::Context>::hc8ba2388a9c045f8
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  21:        0x102da3852 - alloc::sync::Arc<T>::drop_slow::hc4095fd0e6beff7a
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/sync.rs:1061:18
  22:        0x102da40cd - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::h1a0383f1bd120b2d
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/sync.rs:1603:13
  23:        0x102dc00e1 - core::ptr::drop_in_place<alloc::sync::Arc<wgpu::backend::direct::Context>>::hd9f41fbe496df10f
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  24:        0x102dbcba0 - core::ptr::drop_in_place<wgpu::Buffer>::hdb46e02f6fec26d5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  25:        0x102dbd2b1 - core::ptr::drop_in_place<wgpu::util::belt::Chunk>::h5c543dda5d330472
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  26:        0x102db7a33 - core::ptr::drop_in_place<wgpu::util::belt::StagingBelt::recall::{{closure}}::{{closure}}>::h11ba0c51015b2bdf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:178:17
  27:        0x102dba841 - core::ptr::drop_in_place<core::future::from_generator::GenFuture<wgpu::util::belt::StagingBelt::recall::{{closure}}::{{closure}}>>::h298af830c1ebc7c2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  28:        0x102dbb22c - core::ptr::drop_in_place<core::option::Option<core::future::from_generator::GenFuture<wgpu::util::belt::StagingBelt::recall::{{closure}}::{{closure}}>>>::h8dd7ddf55c78f0b1
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  29:        0x102dbb449 - core::ptr::drop_in_place<[core::option::Option<core::future::from_generator::GenFuture<wgpu::util::belt::StagingBelt::recall::{{closure}}::{{closure}}>>]>::h98864a53b60b41ac
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  30:        0x102d74b9f - <alloc::vec::Vec<T,A> as core::ops::drop::Drop>::drop::hddcce69aed536c20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/vec/mod.rs:2722:13
  31:        0x102dbb8a5 - core::ptr::drop_in_place<alloc::vec::Vec<core::option::Option<core::future::from_generator::GenFuture<wgpu::util::belt::StagingBelt::recall::{{closure}}::{{closure}}>>>>::hb2a5affc28d84706
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  32:        0x102b45311 - core::ptr::drop_in_place<wgpu::util::belt::Join<core::future::from_generator::GenFuture<wgpu::util::belt::StagingBelt::recall::{{closure}}::{{closure}}>>>::he7a3b83c930946f4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  33:        0x102b45578 - core::ptr::drop_in_place<alloc::boxed::Box<wgpu::util::belt::Join<core::future::from_generator::GenFuture<wgpu::util::belt::StagingBelt::recall::{{closure}}::{{closure}}>>>>::haaa4c064270ee04c
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  34:        0x102b63035 - core::mem::drop::h756e37bdd81e2296
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/mem/mod.rs:896:24
  35:        0x102b072d2 - futures_task::future_obj::if_alloc::<impl futures_task::future_obj::UnsafeFutureObj<T> for alloc::boxed::Box<F>>::drop::hea90c095afb55b36
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.15/src/future_obj.rs:227:13
  36:        0x10334541c - <futures_task::future_obj::LocalFutureObj<T> as core::ops::drop::Drop>::drop::hb020b01a213312ea
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.15/src/future_obj.rs:90:18
  37:        0x103347891 - core::ptr::drop_in_place<futures_task::future_obj::LocalFutureObj<()>>::h513bf6c7ffd067a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  38:        0x103347745 - core::ptr::drop_in_place<core::option::Option<futures_task::future_obj::LocalFutureObj<()>>>::h8cf41a082fb10040
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  39:        0x10333e760 - futures_util::stream::futures_unordered::FuturesUnordered<Fut>::release_task::h6c7c0e505c86ea2a
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/futures_unordered/mod.rs:260:13
  40:        0x10333e899 - futures_util::stream::futures_unordered::FuturesUnordered<Fut>::clear_head_all::h942f8f8dfd090d75
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/futures_unordered/mod.rs:571:13
  41:        0x10333dc81 - <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as core::ops::drop::Drop>::drop::hf623ccd0a6e56022
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/futures_unordered/mod.rs:582:9
  42:        0x10333bfc5 - core::ptr::drop_in_place<futures_util::stream::futures_unordered::FuturesUnordered<futures_task::future_obj::LocalFutureObj<()>>>::h377bce723acaff38
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  43:        0x102b489c5 - core::ptr::drop_in_place<futures_executor::local_pool::LocalPool>::h093f32d5f1a671bf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  44:        0x102b48d31 - core::ptr::drop_in_place<iced_wgpu::window::compositor::Compositor>::h6e33685cbfe5a6f1
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  45:        0x102b2a530 - iced_winit::application::run_instance::{{closure}}::h3efe4f4770920e3c
                               at /Users/zak/Desktop/iced/winit/src/application.rs:240:1
  46:        0x102ac7b60 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h92fbf5dc7d00b210
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/future/mod.rs:80:19
  47:        0x102b2c083 - iced_winit::application::run::{{closure}}::h8e7620f40dd3d314
                               at /Users/zak/Desktop/iced/winit/src/application.rs:215:24
  48:        0x102afb5f5 - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}::h2d442adaf36f3407
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/app_state.rs:100:13
  49:        0x102afbbaf - winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback::hd3d4ea560204d283
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/app_state.rs:78:13
  50:        0x102afb46a - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::heb584baa03f164ab
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/app_state.rs:99:9
  51:        0x10318b991 - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::hf8ffc3927fc5bc28
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/app_state.rs:205:21
  52:        0x10318da52 - winit::platform_impl::platform::app_state::AppState::cleared::h4a34196d57bcb048
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/app_state.rs:376:13
  53:        0x1031d8e7c - winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}::hfb098e4401151bf8
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/observer.rs:180:21
  54:        0x1031d8cdd - winit::platform_impl::platform::observer::control_flow_handler::{{closure}}::hbe4640f4238ade21
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/observer.rs:142:57
  55:        0x1031c5156 - std::panicking::try::do_call::h5c17687a57223fc4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  56:        0x1031caedb - ___rust_try
  57:        0x1031c4f9e - std::panicking::try::h3bfd82b7c1ea5b8f
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  58:        0x103193405 - std::panic::catch_unwind::h1897b3d2e3d19cc1
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  59:        0x1031a818e - winit::platform_impl::platform::event_loop::stop_app_on_panic::h4fa80b746716c135
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/event_loop.rs:213:11
  60:        0x1031d8b15 - winit::platform_impl::platform::observer::control_flow_handler::he25d37ff84718a02
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/observer.rs:142:5
  61:        0x1031d8e10 - winit::platform_impl::platform::observer::control_flow_end_handler::h02df51f6a91c2721
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/observer.rs:175:9
  62:     0x7fff2060bd01 - <unknown>
  63:     0x7fff2060bb95 - <unknown>
  64:     0x7fff2060b166 - <unknown>
  65:     0x7fff2060a61c - <unknown>
  66:     0x7fff28850a83 - <unknown>
  67:     0x7fff288507e5 - <unknown>
  68:     0x7fff28850583 - <unknown>
  69:     0x7fff22e12172 - <unknown>
  70:     0x7fff22e10945 - <unknown>
  71:     0x7fff22e02c69 - <unknown>
  72:        0x1031fa3a6 - <() as objc::message::MessageArguments>::invoke::ha332b77f04548aad
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  73:        0x1031fadd2 - objc::message::platform::send_unverified::hac15406d40bf7bc3
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  74:        0x102b1059d - objc::message::send_message::hfd6db8c3a792153b
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  75:        0x102b1059d - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}::h3cbc8608788155a9
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/event_loop.rs:174:22
  76:        0x102b66822 - objc::rc::autorelease::autoreleasepool::hb1dad925f4aa87cd
                               at /Users/zak/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/rc/autorelease.rs:29:5
  77:        0x102b101a8 - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::h38d08c20c4ad75ad
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/event_loop.rs:164:9
  78:        0x102b115ec - winit::platform_impl::platform::event_loop::EventLoop<T>::run::he31eff5aaeb10844
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/platform_impl/macos/event_loop.rs:143:9
  79:        0x102b69373 - winit::event_loop::EventLoop<T>::run::hc70e69c0677cffe7
                               at /Users/zak/.cargo/git/checkouts/winit-57d3141eaf559308/24a75a7/src/event_loop.rs:154:9
  80:        0x102b2bcbd - iced_winit::application::run::h8436285a716464b9
                               at /Users/zak/Desktop/iced/winit/src/application.rs:190:5
  81:        0x102ad53cc - iced::application::Application::run::h3cc3659f62e26318
                               at /Users/zak/Desktop/iced/src/application.rs:221:16
  82:        0x102b69d79 - todos::main::hc28c1a03a0c7b655
                               at /Users/zak/Desktop/iced/examples/todos/src/main.rs:9:5
  83:        0x102b41cc5 - core::ops::function::FnOnce::call_once::h42c68d48ae65ab36
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  84:        0x102adffdc - std::sys_common::backtrace::__rust_begin_short_backtrace::h8af11c5d5f6d48fd
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:125:18
  85:        0x102b399a8 - std::rt::lang_start::{{closure}}::h37be1d6ccb2d3578
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:63:18
  86:        0x10336a669 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5adc1669b25f044b
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  87:        0x10336a669 - std::panicking::try::do_call::h405f88a3fec16587
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  88:        0x10336a669 - std::panicking::try::h86d9af92fb3c6022
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  89:        0x10336a669 - std::panic::catch_unwind::h67150880d2b87901
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  90:        0x10336a669 - std::rt::lang_start_internal::{{closure}}::h548e43d03023c928
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  91:        0x10336a669 - std::panicking::try::do_call::h1383affbfec23244
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  92:        0x10336a669 - std::panicking::try::hf51149bda74e8587
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  93:        0x10336a669 - std::panic::catch_unwind::h8280208a4f5e7cf4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  94:        0x10336a669 - std::rt::lang_start_internal::h5f9b030f0a63c040
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  95:        0x102b3996e - std::rt::lang_start::hd09c3e814566f2c4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:62:5
  96:        0x102b6e1c6 - _main
thread panicked while panicking. aborting.
fish: Job 1, 'cargo run --package todos' terminated by signal SIGILL (Illegal instruction)```

**Comment by hecrj** [comment]
Good catch! I can reproduce.

This was probably introduced by #670. I'm working on a fix!

**Comment by hecrj** [comment]
I just opened #1046 with a fix. Let me know if it works for you!
