### ISSUE TITLE
Can't run on Wayland, X11 works.

### ISSUE THREAD

**Issue by vitw** [iced-rs/iced#1073]
when I try to run Counter example on my machine with KDE Plasma installed in Wayland session I get a seg fault. On X11 everything works well though.
```
_./icedtest 
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
error marshalling arguments for create_prime_buffer: dup failed: Bad file descriptor
Error marshalling request: Bad file descriptor
thread 'main' panicked at 'Next frame: Outdated', /home/vp/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.4.0/src/window/compositor.rs:126:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault
```
Results with backtrace:
```
RUST_BACKTRACE=1 ./icedtest 
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
error marshalling arguments for create_prime_buffer: dup failed: Bad file descriptor
Error marshalling request: Bad file descriptor
thread 'main' panicked at 'Next frame: Outdated', /home/vp/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.4.0/src/window/compositor.rs:126:52
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: <iced_wgpu::window::compositor::Compositor as iced_graphics::window::compositor::Compositor>::draw
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: iced_winit::application::run::{{closure}}
   6: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run
   7: winit::platform_impl::platform::EventLoop<T>::run
   8: winit::event_loop::EventLoop<T>::run
   9: iced_winit::application::run
  10: icedtest::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Segmentation fault
```

**Comment by inoshy** [comment]
wayland support is in the distant horizon.
