### ISSUE TITLE
error matching FRAGMENT shader requirements

### ISSUE THREAD

**Issue by irrenhaus** [iced-rs/iced#1135]
Hello,

I'm unable to run anything using the current master of iced @ 26d053ab3887b73f854a1174864d0fec221c5c9b due to an error "error matching FRAGMENT shader requirements against the pipeline".

This happened first while trying to get up and running with my own application using iced. I then verified by checking out the current master branch and building the `counter` example. Both have the same error during startup.

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `$HOME/_tmp/iced/target/debug/counter`
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    error matching FRAGMENT shader requirements against the pipeline
    unable to filter the texture (ResourceBinding { group: 0, binding: 2 }) by the sampler (ResourceBinding { group: 0, binding: 1 })
    non-filterable float texture

', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.1/src/backend/direct.rs:2195:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:460:5
   2: wgpu::backend::direct::default_error_handler
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.1/src/backend/direct.rs:2195:5
   3: core::ops::function::Fn::call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:70:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1705:9
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.1/src/backend/direct.rs:2183:9
   6: wgpu::backend::direct::Context::handle_error
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.1/src/backend/direct.rs:184:9
   7: <wgpu::backend::direct::Context as wgpu::Context>::device_create_render_pipeline
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.1/src/backend/direct.rs:1276:13
   8: wgpu::Device::create_render_pipeline
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.1/src/lib.rs:1770:17
   9: wgpu_glyph::pipeline::build
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu_glyph-0.15.1/src/pipeline.rs:290:15
  10: wgpu_glyph::pipeline::Pipeline<()>::new
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu_glyph-0.15.1/src/pipeline.rs:34:9
  11: wgpu_glyph::GlyphBrush<(),F,H>::new
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu_glyph-0.15.1/src/lib.rs:221:23
  12: wgpu_glyph::builder::GlyphBrushBuilder<(),F,H>::build
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu_glyph-0.15.1/src/builder.rs:113:9
  13: iced_wgpu::text::Pipeline::new
             at $HOME/_tmp/iced/wgpu/src/text.rs:52:13
  14: iced_wgpu::backend::Backend::new
             at $HOME/_tmp/iced/wgpu/src/backend.rs:40:29
  15: iced_wgpu::window::compositor::Compositor::create_backend
             at $HOME/_tmp/iced/wgpu/src/window/compositor.rs:84:9
  16: <iced_wgpu::window::compositor::Compositor as iced_graphics::window::compositor::Compositor>::new
             at $HOME/_tmp/iced/wgpu/src/window/compositor.rs:103:23
  17: iced_winit::application::run
             at $HOME/_tmp/iced/winit/src/application.rs:163:34
  18: iced::application::Application::run
             at $HOME/_tmp/iced/src/application.rs:215:16
  19: iced::sandbox::Sandbox::run
             at $HOME/_tmp/iced/src/sandbox.rs:144:9
  20: counter::main
             at ./src/main.rs:6:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

**Comment by horasal** [comment]
This is caused by a bug in upstream crate `wgpu_glyph`: https://github.com/hecrj/wgpu_glyph/issues/81 .

It has been fixed in the master but haven't got a release so you can patch dependency in your project's `Cargo.toml` by adding the following lines:

```toml
[patch.crates-io]
wgpu_glyph = { git = "https://github.com/hecrj/wgpu_glyph", branch="master" }
```

**Comment by irrenhaus** [comment]
Nice, thanks a lot!
