### ISSUE TITLE
Occurence of issue that had been fixed with PR in wgpu-core

### ISSUE THREAD

**Issue by feelingnothing** [iced-rs/iced#1152]
Couldn't compile any examples on Windows 21H2 (OS Build 19044.1348)
Windows pop ups for a fraction of a second and crashes with this
I traced it to [this](https://github.com/gfx-rs/wgpu/pull/2188) PR that has been merged and released at `0.11.1` which `iced_wgpu` includes as dependencies, I'll open issue here and maybe populate it to wgpu as well if it is a certain issue with wgpu
EDIT: I did compile examples from `master` branch by directly cloning it
Full Backtrace:
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    error matching FRAGMENT shader requirements against the pipeline
    unable to filter the texture (ResourceBinding { group: 0, binding: 2 }) by the sampler (ResourceBinding { group: 0, binding: 1 })
    non-filterable float texture

', C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2195:5
stack backtrace:
   0:     0x7ff77fe3e58e - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff77fe3e58e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff77fe3e58e - std::sys_common::backtrace::_print_fmt
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff77fe3e58e - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff77fe5545a - core::fmt::write
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\fmt\mod.rs:1150
   5:     0x7ff77fe3c078 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\io\mod.rs:1667
   6:     0x7ff77fe40a56 - std::sys_common::backtrace::_print
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff77fe40a56 - std::sys_common::backtrace::print
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff77fe40a56 - std::panicking::default_hook::closure$1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:210
   9:     0x7ff77fe40544 - std::panicking::default_hook
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:227
  10:     0x7ff77fe410b5 - std::panicking::rust_panic_with_hook
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:624
  11:     0x7ff77fe40c9b - std::panicking::begin_panic_handler::closure$0
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:521
  12:     0x7ff77fe3eed7 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff77fe40bf9 - std::panicking::begin_panic_handler
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:517
  14:     0x7ff77fe5cb2c - std::panicking::begin_panic_fmt
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:460
  15:     0x7ff77f71945a - wgpu::backend::direct::default_error_handler
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2195
  16:     0x7ff77f67884d - core::ops::function::Fn::call<void (*)(enum$<wgpu::Error>),tuple$<enum$<wgpu::Error> > >
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\ops\function.rs:70
  17:     0x7ff77f6e3584 - alloc::boxed::impl$46::call<tuple$<enum$<wgpu::Error> >,dyn$<wgpu::UncapturedErrorHandler,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\alloc\src\boxed.rs:1650
  18:     0x7ff77f719268 - wgpu::backend::direct::ErrorSinkRaw::handle_error
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2183
  19:     0x7ff77f70f906 - wgpu::backend::direct::Context::handle_error<enum$<wgpu_core::pipeline::CreateRenderPipelineError> >
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:184
  20:     0x7ff77f71522e - wgpu::backend::direct::impl$3::device_create_render_pipeline
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:1276
  21:     0x7ff77f77422f - wgpu::Device::create_render_pipeline
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\lib.rs:1770
  22:     0x7ff77f56b1e1 - wgpu_glyph::pipeline::build<tuple$<> >
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu_glyph-0.15.1\src\pipeline.rs:290
  23:     0x7ff77f56a326 - wgpu_glyph::pipeline::Pipeline<tuple$<> >::new
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu_glyph-0.15.1\src\pipeline.rs:34
  24:     0x7ff77f53ee21 - wgpu_glyph::GlyphBrush<tuple$<>,ab_glyph::font_arc::FontArc,twox_hash::std_support::sixty_four::RandomXxHashBuilder64>::new<ab_glyph::font_arc::FontArc,twox_hash::std_support::sixty_four::RandomXxHashBuilder64>
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu_glyph-0.15.1\src\lib.rs:221
  25:     0x7ff77f53d065 - wgpu_glyph::builder::GlyphBrushBuilder<tuple$<>,ab_glyph::font_arc::FontArc,twox_hash::std_support::sixty_four::RandomXxHashBuilder64>::build<ab_glyph::font_arc::FontArc,twox_hash::std_support::sixty_four::RandomXxHashBuilder64>
                               at C:\Users\USERNAME\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu_glyph-0.15.1\src\builder.rs:113
  26:     0x7ff77f4ed1ce - iced_wgpu::text::Pipeline::new
                               at C:\Users\USERNAME\CLionProjects\iced\wgpu\src\text.rs:52
  27:     0x7ff77f4caa29 - iced_wgpu::backend::Backend::new
                               at C:\Users\USERNAME\CLionProjects\iced\wgpu\src\backend.rs:40
  28:     0x7ff77f4e3c3f - iced_wgpu::window::compositor::Compositor::create_backend
                               at C:\Users\USERNAME\CLionProjects\iced\wgpu\src\window\compositor.rs:84
  29:     0x7ff77f49e891 - iced_wgpu::window::compositor::impl$1::new<winit::window::Window>
                               at C:\Users\USERNAME\CLionProjects\iced\wgpu\src\window\compositor.rs:103
  30:     0x7ff77f4778f9 - iced_winit::application::run<iced::application::Instance<scrollable::ScrollableDemo>,iced_futures::executor::null::Null,iced_wgpu::window::compositor::Compositor>
                               at C:\Users\USERNAME\CLionProjects\iced\winit\src\application.rs:163
  31:     0x7ff77f4bbc8d - iced::application::Application::run<scrollable::ScrollableDemo>
                               at C:\Users\USERNAME\CLionProjects\iced\src\application.rs:215
  32:     0x7ff77f4bc000 - iced::sandbox::Sandbox::run<scrollable::ScrollableDemo>
                               at C:\Users\USERNAME\CLionProjects\iced\src\sandbox.rs:144
  33:     0x7ff77f4a4c2a - scrollable::main
                               at C:\Users\USERNAME\CLionProjects\iced\examples\scrollable\src\main.rs:9
  34:     0x7ff77f4a7233 - core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,enum$<iced::error::Error> >, 0, 2, Err> (*)(),tuple$<> >
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\ops\function.rs:227
  35:     0x7ff77f4c5c86 - std::sys_common::backtrace::__rust_begin_short_backtrace<enum$<core::result::Result<tuple$<>,enum$<iced::error::Error> >, 0, 2, Err> (*)(),enum$<core::result::Result<tuple$<>,enum$<iced::error::Error> >, 0, 2, Err> >
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\sys_common\backtrace.rs:125
  36:     0x7ff77f45b416 - std::rt::lang_start::closure$0<enum$<core::result::Result<tuple$<>,enum$<iced::error::Error> >, 0, 2, Err> >
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\rt.rs:63
  37:     0x7ff77fe41646 - core::ops::function::impls::impl$2::call_once
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\ops\function.rs:259
  38:     0x7ff77fe41646 - std::panicking::try::do_call
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:403
  39:     0x7ff77fe41646 - std::panicking::try
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:367
  40:     0x7ff77fe41646 - std::panic::catch_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panic.rs:129
  41:     0x7ff77fe41646 - std::rt::lang_start_internal::closure$2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\rt.rs:45
  42:     0x7ff77fe41646 - std::panicking::try::do_call
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:403
  43:     0x7ff77fe41646 - std::panicking::try
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:367
  44:     0x7ff77fe41646 - std::panic::catch_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panic.rs:129
  45:     0x7ff77fe41646 - std::rt::lang_start_internal
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\rt.rs:45
  46:     0x7ff77f45b3df - std::rt::lang_start<enum$<core::result::Result<tuple$<>,enum$<iced::error::Error> >, 0, 2, Err> >
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\std\src\rt.rs:62
  47:     0x7ff77f4a5dd6 - main
  48:     0x7ff77fe5bad0 - invoke_main
                               at d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  49:     0x7ff77fe5bad0 - __scrt_common_main_seh
                               at d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  50:     0x7ffcae4d7034 - BaseThreadInitThunk
  51:     0x7ffcb01c2651 - RtlUserThreadStart
error: process didn't exit successfully: `C:\Users\USERNAME\.cargo\debug\scrollable.exe` (exit code: 101)

Process finished with exit code 101
```

**Comment by hecrj** [comment]
This issue has been fixed in [the latest release of `wgpu_glyph`](https://github.com/hecrj/wgpu_glyph/releases/tag/0.15.2).

Could you run `cargo update` and try again?
