### ISSUE TITLE
Panic with large image loading on Windows 10

### ISSUE THREAD

**Issue by Amazingkenneth** [iced-rs/iced#1746]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

The `tour` example crashed after I replaced `ferris.png` with a large JPG image (917 KB, 1920 x 2880) on Windows 10, but it worked well on Windows 11. As I am testing it in VirtualBox, this is the screen record:

https://user-images.githubusercontent.com/81886982/222883251-4b69fb54-6664-4bbd-a399-5affb97b115a.mp4

The code for representation:

[tour.zip](https://github.com/iced-rs/iced/files/10887765/tour.zip)

### What is the expected behavior?

The program can load out the image slowly, but should not panic and crash.

### Version

master

### Operative System

Windows

### Do you have any log output?

```shell
PS C:\Users\vboxuser\iced-master\examples\tour> $Env:RUST_BACKTRACE=1
PS C:\Users\vboxuser\iced-master\examples\tour> ls -r


    Directory: C:\Users\vboxuser\iced-master\examples\tour


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          3/4/2023   3:19 PM                images
d-----          3/4/2023   2:47 PM                src
------          3/3/2023  12:20 PM            228 Cargo.toml
------          3/3/2023  12:20 PM            359 index.html
------          3/3/2023  12:20 PM            933 README.md


    Directory: C:\Users\vboxuser\iced-master\examples\tour\images


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
------          3/3/2023  12:20 PM          16289 ferris.png
-a----          3/4/2023   3:18 PM         938034 LargeImage.jpg


    Directory: C:\Users\vboxuser\iced-master\examples\tour\src


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          3/4/2023   3:21 PM          20579 main.rs


PS C:\Users\vboxuser\iced-master\examples\tour> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `C:\Users\vboxuser\iced-master\target\debug\tour.exe`
PS C:\Users\vboxuser\iced-master\examples\tour> .\images\LargeImage.jpg
PS C:\Users\vboxuser\iced-master\examples\tour> notepad .\src\main.rs
PS C:\Users\vboxuser\iced-master\examples\tour> cargo run
   Compiling tour v0.1.0 (C:\Users\vboxuser\iced-master\examples\tour)
    Finished dev [unoptimized + debuginfo] target(s) in 32.37s
     Running `C:\Users\vboxuser\iced-master\target\debug\tour.exe`
[2023-03-04T07:25:37Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandList::CopyTextureRegion: The region specified by D3D12_TEXTURE_COPY_LOCATION:PlacedFootprint extends past the end of the buffer it is placed on. The size required by PlacedFootprint is 22118400, as the fields of PlacedFootprint::Placement are as follows: RowPitch is 7680, Height is 2880, and Format is R8G8B8A8_UNORM_SRGB. PlacedFootprint::Offset is 15728640, which requires the buffer to have 37847040 bytes; but the buffer only has 22118400 bytes. [ RESOURCE_MANIPULATION ERROR #869: COPYTEXTUREREGION_INVALIDSRCPLACEMENT]
[2023-03-04T07:25:38Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: Command lists must be successfully closed before execution. [ EXECUTION ERROR #838: EXECUTECOMMANDLISTS_FAILEDCOMMANDLIST]
[2023-03-04T07:25:38Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_INVALID_CALL: There is strong evidence that the application has performed an illegal or undefined operation, and such a condition could not be returned to the application cleanly through a return code). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]
[2023-03-04T07:25:38Z ERROR wgpu_hal::auxil::dxgi::result] Map buffer failed: 0x887A0005
[2023-03-04T07:25:38Z ERROR wgpu_core::device::life] Mapping failed Device(Lost)
[2023-03-04T07:25:40Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandList::Close: An ID3D12Resource object (0x0000022DD178CB40:'iced_wgpu::image texture atlas'), referenced in the command list being closed (0x0000022DD2AA14D0:'iced_wgpu encoder (debug layer indirect)'), was deleted prior to closing the command list.  This is invalid and can result in application instability. [ EXECUTION ERROR #921: OBJECT_DELETED_WHILE_STILL_IN_USE]
[2023-03-04T07:25:40Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12GraphicsCommandList::*: This API cannot be called on a closed command list. [ EXECUTION ERROR #547: COMMAND_LIST_CLOSED]
[2023-03-04T07:25:40Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: An ID3D12Resource object (0x0000022DD178CB40:'iced_wgpu::image texture atlas') referenced in a command list (0x0000022DD2B3C040:'iced_wgpu encoder') was deleted prior to executing the command list.  This is invalid and can result in application instability. [ EXECUTION ERROR #921: OBJECT_DELETED_WHILE_STILL_IN_USE]
[2023-03-04T07:25:40Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: Using CopyTextureRegion on Command List (0x0000022DD2B3C040:'iced_wgpu encoder'): Resource state (0xC0: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE|D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE) of resource (0x0000022DD28A9760:'iced_wgpu::image texture atlas') (subresource: 0) is invalid for use as a destination resource.  Expected State Bits (all): 0x400: D3D12_RESOURCE_STATE_COPY_DEST, Actual State: 0xC0: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE|D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE, Missing State: 0x400: D3D12_RESOURCE_STATE_COPY_DEST. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
[2023-03-04T07:25:40Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: Using CopyBufferRegion on Command List (0x0000022DD2B3C040:'iced_wgpu encoder'): Resource state (0x1: D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER) of resource (0x0000022DD178AB50:'iced_wgpu::image uniforms buffer') (subresource: 0) is invalid for use as a destination buffer.  Expected State Bits (all): 0x400: D3D12_RESOURCE_STATE_COPY_DEST, Actual State: 0x1: D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER, Missing State: 0x400: D3D12_RESOURCE_STATE_COPY_DEST. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
[2023-03-04T07:25:40Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: Using CopyBufferRegion on Command List (0x0000022DD2B3C040:'iced_wgpu encoder'): Resource state (0x1: D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER) of resource (0x0000022DD178A230:'iced_wgpu::image instance buffer') (subresource: 0) is invalid for use as a destination buffer.  Expected State Bits (all): 0x400: D3D12_RESOURCE_STATE_COPY_DEST, Actual State: 0x1: D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER, Missing State: 0x400: D3D12_RESOURCE_STATE_COPY_DEST. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
[2023-03-04T07:25:40Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12CommandQueue::ExecuteCommandLists: Command lists must be successfully closed before execution. [ EXECUTION ERROR #838: EXECUTECOMMANDLISTS_FAILEDCOMMANDLIST]
[2023-03-04T07:25:40Z ERROR wgpu_hal::auxil::dxgi::result] Map buffer failed: 0x887A0005
[2023-03-04T07:25:40Z ERROR wgpu_core::device::life] Mapping failed Device(Lost)
thread 'main' panicked at 'Error in Buffer::get_mapped_range: buffer is not mapped', C:\Users\vboxuser\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:274:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
   2: wgpu::backend::direct::Context::handle_error_fatal<enum2$<wgpu_core::resource::BufferAccessError> >
             at C:\Users\vboxuser\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:274
   3: wgpu::backend::direct::impl$3::buffer_get_mapped_range
             at C:\Users\vboxuser\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:1724
   4: wgpu::BufferSlice::get_mapped_range_mut
             at C:\Users\vboxuser\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\lib.rs:2599
   5: wgpu::util::belt::StagingBelt::write_buffer
             at C:\Users\vboxuser\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\util\belt.rs:120
   6: iced_wgpu::quad::Pipeline::draw
             at C:\Users\vboxuser\iced-master\wgpu\src\quad.rs:185
   7: iced_wgpu::backend::Backend::flush
             at C:\Users\vboxuser\iced-master\wgpu\src\backend.rs:128
   8: iced_wgpu::backend::Backend::present<alloc::string::String>
             at C:\Users\vboxuser\iced-master\wgpu\src\backend.rs:94
   9: iced_wgpu::window::compositor::impl$1::present::closure$0<enum2$<iced_style::theme::Theme>,alloc::string::String>
             at C:\Users\vboxuser\iced-master\wgpu\src\window\compositor.rs:228
  10: iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend,enum2$<iced_style::theme::Theme> >::with_primitives<iced_wgpu::backend::Backend,enum2$<iced_style::theme::Theme>,iced_wgpu::window::compositor::impl$1::present::closure_env$0<enum2$<iced_style:
             at C:\Users\vboxuser\iced-master\graphics\src\renderer.rs:46
  11: iced_wgpu::window::compositor::impl$1::present<enum2$<iced_style::theme::Theme>,alloc::string::String>
             at C:\Users\vboxuser\iced-master\wgpu\src\window\compositor.rs:227
  12: iced_winit::application::run_instance::async_fn$0<iced::application::Instance<tour::Tour>,iced_futures::backend::null::Executor,iced_wgpu::window::compositor::Compositor<enum2$<iced_style::theme::Theme> > >
             at C:\Users\vboxuser\iced-master\winit\src\application.rs:532
  13: iced_winit::application::run::closure$1<iced::application::Instance<tour::Tour>,iced_futures::backend::null::Executor,iced_wgpu::window::compositor::Compositor<enum2$<iced_style::theme::Theme> > >
             at C:\Users\vboxuser\iced-master\winit\src\application.rs:247
  14: winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<enum2$<tour::Message>,iced_winit::application::run::closure_env$1<iced::application::Instance<tour::Tour>,iced_futures::backend::null::Executor,iced_wgpu::window::compositor::Compos
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:254
  15: alloc::boxed::impl$46::call_mut<tuple$<enum2$<winit::event::Event<enum2$<tour::Message> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<enum2$<tour::Message> > >,ref_mut$<enum2$<win
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\alloc\src\boxed.rs:2016
  16: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop\runner.rs:247
  17: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<tour::Message> > >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\panic\unwind_safe.rs:271
  18: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<tour::Message> > >,tuple$<> >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:483
  19: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> > >,isize>
  20: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<tour::Message> > > >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:447
  21: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<tour::Message> > >,tuple$<> >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panic.rs:137
  22: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<tour::Message> >::catch_unwind<enum2$<tour::Message>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop\runner.rs:154
  23: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<tour::Message> >::call_event_handler<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop\runner.rs:239
  24: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<tour::Message> >::send_event<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop\runner.rs:212
  25: winit::platform_impl::platform::event_loop::WindowData<enum2$<tour::Message> >::send_event<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:143
  26: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:1028
  27: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> >,tuple$<> >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:507
  28: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> > >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\panic\unwind_safe.rs:271
  29: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> > >,isize>
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:483
  30: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> > >,isize>
  31: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> > > >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:447
  32: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> > >,isize>
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panic.rs:137
  33: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<tour::Message> >::catch_unwind<enum2$<tour::Message>,isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> > >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop\runner.rs:154
  34: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:2209
  35: winit::platform_impl::platform::event_loop::public_window_callback<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:937
  36: CallWindowProcW
  37: DispatchMessageW
  38: SendMessageTimeoutW
  39: KiUserCallbackDispatcher
  40: NtUserDispatchMessage
  41: DispatchMessageW
  42: winit::platform_impl::platform::event_loop::flush_paint_messages::closure$0<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:772
  43: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<tour::Message> >::owned_windows<enum2$<tour::Message>,winit::platform_impl::platform::event_loop::flush_paint_messages::closure_env$0<enum2$<tour::Message> > >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop\runner.rs:192
  44: winit::platform_impl::platform::event_loop::flush_paint_messages<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:755
  45: winit::platform_impl::platform::event_loop::thread_event_target_callback::closure$0<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:2259
  46: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<tour::Message> >,tuple$<> >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:507
  47: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<tour::Message> > >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\panic\unwind_safe.rs:271
  48: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<tour::Message> > >,isize>
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:483
  49: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<enum2$<tour::Message> > >,isize>
  50: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<tour::Message> > > >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panicking.rs:447
  51: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<tour::Message> > >,isize>
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\panic.rs:137
  52: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<tour::Message> >::catch_unwind<enum2$<tour::Message>,isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<enum2$<tour::Message> > >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop\runner.rs:154
  53: winit::platform_impl::platform::event_loop::thread_event_target_callback<enum2$<tour::Message> >
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:2436
  54: CallWindowProcW
  55: DispatchMessageW
  56: SendMessageTimeoutW
  57: KiUserCallbackDispatcher
  58: NtUserDispatchMessage
  59: DispatchMessageW
  60: winit::platform_impl::platform::event_loop::EventLoop<enum2$<tour::Message> >::run_return<enum2$<tour::Message>,iced_winit::application::run::closure_env$1<iced::application::Instance<tour::Tour>,iced_futures::backend::null::Executor,iced_wgpu::window::co
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform_impl\windows\event_loop.rs:276
  61: winit::platform::run_return::impl$0::run_return<enum2$<tour::Message>,iced_winit::application::run::closure_env$1<iced::application::Instance<tour::Tour>,iced_futures::backend::null::Executor,iced_wgpu::window::compositor::Compositor<enum2$<iced_style::th
             at C:\Users\vboxuser\.cargo\git\checkouts\winit-57d3141eaf559308\9404575\src\platform\run_return.rs:62
  62: iced_winit::application::platform::run<enum2$<tour::Message>,iced_winit::application::run::closure_env$1<iced::application::Instance<tour::Tour>,iced_futures::backend::null::Executor,iced_wgpu::window::compositor::Compositor<enum2$<iced_style::theme::Them
             at C:\Users\vboxuser\iced-master\winit\src\application.rs:874
  63: iced_winit::application::run<iced::application::Instance<tour::Tour>,iced_futures::backend::null::Executor,iced_wgpu::window::compositor::Compositor<enum2$<iced_style::theme::Theme> > >
             at C:\Users\vboxuser\iced-master\winit\src\application.rs:222
  64: iced::application::Application::run<tour::Tour>
             at C:\Users\vboxuser\iced-master\src\application.rs:209
  65: iced::sandbox::Sandbox::run<tour::Tour>
             at C:\Users\vboxuser\iced-master\src\sandbox.rs:153
  66: tour::main
             at .\src\main.rs:13
  67: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<iced::error::Error> > > (*)(),tuple$<> >
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\Users\vboxuser\iced-master\target\debug\tour.exe` (exit code: 101)
```

**Comment by hecrj** [comment]
This seems like a staging belt issue. It may be fixed in the `advanced-text` branch.
