### ISSUE TITLE
tour example crashes when resizing to 0

### ISSUE THREAD

**Issue by adals** [iced-rs/iced#1773]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

my os mac m1 pro

branch advanced-text 

when resize tour example to 0 it crashed

### What is the expected behavior?

works normally 

### Version

master

### Operative System

macOS

### Do you have any log output?

```shell
cd tour
RUST_BACKTRACE=full cargo run

Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `/Users/adelalharbi/Projects/Rust/proj02/iced/target/debug/tour`
thread 'main' panicked at 'attempt to subtract with overflow', /Users/adelalharbi/.cargo/git/checkouts/cosmic-text-92dc585b4973ff15/e788c17/src/buffer.rs:246:17
stack backtrace:
   0:        0x1051d1660 - std::backtrace_rs::backtrace::libunwind::trace::h31c2dbb633cb650a
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1051d1660 - std::backtrace_rs::backtrace::trace_unsynchronized::h6c3a20bf26fdb319
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1051d1660 - std::sys_common::backtrace::_print_fmt::h4983cc2fef86eb80
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x1051d1660 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfbd99529d8ecd76d
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1051ea36c - core::fmt::write::h9d97190441ee1d43
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/fmt/mod.rs:1254:17
   5:        0x1051cece8 - std::io::Write::write_fmt::h8e549a8786c022b9
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/io/mod.rs:1698:15
   6:        0x1051d1474 - std::sys_common::backtrace::_print::h4967f644a7b7f093
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x1051d1474 - std::sys_common::backtrace::print::hcdd2ae2f7b4f384b
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x1051d2aa4 - std::panicking::default_hook::{{closure}}::h2a46a28a68dc3d98
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:271:22
   9:        0x1051d2864 - std::panicking::default_hook::h9a2d7764b010ec79
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:290:9
  10:        0x1051d2f7c - std::panicking::rust_panic_with_hook::h65330bb1b8d3241c
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:692:13
  11:        0x1051d2e70 - std::panicking::begin_panic_handler::{{closure}}::h343dfc740ec0e358
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:581:13
  12:        0x1051d1a80 - std::sys_common::backtrace::__rust_end_short_backtrace::hc5295e27637ab888
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/sys_common/backtrace.rs:150:18
  13:        0x1051d2c44 - rust_begin_unwind
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:579:5
  14:        0x105216a74 - core::panicking::panic_fmt::h2fc7f604365b2fbe
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/panicking.rs:67:14
  15:        0x105216ae4 - core::panicking::panic::hf25fee583223a2d0
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/panicking.rs:117:5
  16:        0x1047201b0 - <cosmic_text::buffer::LayoutRunIter as core::iter::traits::iterator::Iterator>::next::h0aa2795ff368754a
                               at /Users/adelalharbi/.cargo/git/checkouts/cosmic-text-92dc585b4973ff15/e788c17/src/buffer.rs:246:17
  17:        0x1046c07c8 - core::iter::traits::iterator::Iterator::fold::hc6b8bdae65ba77e1
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/iter/traits/iterator.rs:2481:29
  18:        0x1046d88b4 - <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::h9050819de0b1ba38
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/iter/adapters/enumerate.rs:112:9
  19:        0x1046bc024 - iced_wgpu::text::Pipeline::prepare::{{closure}}::h6e487bee16eb986e
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/wgpu/src/text.rs:103:48
  20:        0x1046bbe34 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h28a5b03998fe8142
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/ops/function.rs:310:13
  21:        0x1046b60d4 - core::option::Option<T>::map::he6d919cec7676c01
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/option.rs:1101:29
  22:        0x1046d5020 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h3b3e10b9b50a05e7
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/iter/adapters/map.rs:103:9
  23:        0x1046be890 - glyphon::text_render::TextRenderer::prepare::h6c01d5bbb57afee9
                               at /Users/adelalharbi/.cargo/git/checkouts/glyphon-70ff9ac92aaa9d8a/4705017/src/text_render.rs:78:26
  24:        0x1046d7074 - iced_wgpu::text::Pipeline::prepare::h962d39f8f93498dc
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/wgpu/src/text.rs:143:22
  25:        0x1046d1490 - iced_wgpu::backend::Backend::prepare_text::hac811efc697c18d5
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/wgpu/src/backend.rs:141:21
  26:        0x1044a3658 - iced_wgpu::backend::Backend::present::h34bb8e8d6a02090d
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/wgpu/src/backend.rs:99:16
  27:        0x1044a271c - iced_wgpu::window::compositor::present::h93d0054298232730
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/wgpu/src/window/compositor.rs:157:13
  28:        0x1044f7d78 - <iced_renderer::compositor::Compositor<Theme> as iced_graphics::compositor::Compositor>::present::{{closure}}::h985941234d251b18
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/renderer/src/compositor.rs:154:22
  29:        0x10445f7a0 - iced_graphics::renderer::Renderer<B,T>::with_primitives::h20abafec2a17263d
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/graphics/src/renderer.rs:51:9
  30:        0x1044f7b6c - <iced_renderer::compositor::Compositor<Theme> as iced_graphics::compositor::Compositor>::present::he130d5e6393aaddf
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/renderer/src/compositor.rs:147:9
  31:        0x104464c78 - iced_winit::application::run_instance::{{closure}}::hef2cb5e975d708ee
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/winit/src/application.rs:528:23
  32:        0x104467038 - iced_winit::application::run::{{closure}}::h654db0970dab2cbd
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/winit/src/application.rs:247:24
  33:        0x1045075d0 - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}::h997ce8024a89299a
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/app_state.rs:106:17
  34:        0x104507948 - winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback::h114cc5d3fa513caa
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/app_state.rs:80:13
  35:        0x104507404 - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::he5db83aa16e776f9
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/app_state.rs:101:9
  36:        0x10462460c - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::hddbe2524bc032fa3
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/app_state.rs:209:21
  37:        0x104626370 - winit::platform_impl::platform::app_state::AppState::cleared::ha6d300cdd7b9fba5
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/app_state.rs:396:13
  38:        0x10465a254 - winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}::h22607d01ec04bfbe
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/observer.rs:184:21
  39:        0x10465a02c - winit::platform_impl::platform::observer::control_flow_handler::{{closure}}::h0299ac10e79028c9
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/observer.rs:145:9
  40:        0x10461baf4 - std::panicking::try::do_call::h823c04d4a307b185
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:487:40
  41:        0x10461dd54 - ___rust_try
  42:        0x10461ba0c - std::panicking::try::hc0501fbc14c5f6ca
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:451:19
  43:        0x10461e980 - std::panic::catch_unwind::h462f8cfe7e584ebb
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panic.rs:140:14
  44:        0x10464d21c - winit::platform_impl::platform::event_loop::stop_app_on_panic::haf9a336c05d34d4f
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/event_loop.rs:265:11
  45:        0x104659e64 - winit::platform_impl::platform::observer::control_flow_handler::h2058f4782b9d412d
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/observer.rs:143:5
  46:        0x10465a1cc - winit::platform_impl::platform::observer::control_flow_end_handler::h1a8c092ceb296ef4
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/observer.rs:179:9
  47:        0x1a55a8db8 - <unknown>
  48:        0x1a55a8ca4 - <unknown>
  49:        0x1a55a83e4 - <unknown>
  50:        0x1a55a7878 - <unknown>
  51:        0x1aec87fa0 - <unknown>
  52:        0x1aec87de4 - <unknown>
  53:        0x1aec87b2c - <unknown>
  54:        0x1a882d84c - <unknown>
  55:        0x1a882c9dc - <unknown>
  56:        0x1a8b10cc8 - <unknown>
  57:        0x1a8a31878 - <unknown>
  58:        0x1a8a3166c - <unknown>
  59:        0x1a8aa5630 - <unknown>
  60:        0x1a89d1628 - <unknown>
  61:        0x1a895b844 - <unknown>
  62:        0x1a895aeb0 - <unknown>
  63:        0x1a8959fe8 - <unknown>
  64:        0x1046ac2e4 - <(A,) as objc::message::MessageArguments>::invoke::hfe28ce50f9aeca65
                               at /Users/adelalharbi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:128:17
  65:        0x10464923c - objc::message::platform::send_super_unverified::h634ec44b584dde45
                               at /Users/adelalharbi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:38:9
  66:        0x10465895c - objc::message::send_super_message::h594b6b0ac16390b5
                               at /Users/adelalharbi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:205:5
  67:        0x10465895c - winit::platform_impl::platform::app::send_event::h0e510f523e48704a
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/app.rs:53:25
  68:        0x1a8bac098 - <unknown>
  69:        0x1a8820e30 - <unknown>
  70:        0x104cdd834 - <() as objc::message::MessageArguments>::invoke::ha3184f7787364788
                               at /Users/adelalharbi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:128:17
  71:        0x104ccdd60 - objc::message::platform::send_unverified::h59f95eaf5b0197f2
                               at /Users/adelalharbi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:27:9
  72:        0x1044d541c - objc::message::send_message::h72bdb85397b7143a
                               at /Users/adelalharbi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:178:5
  73:        0x1044d541c - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}::hc759443a3419edb9
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/event_loop.rs:222:25
  74:        0x1044fe71c - objc::rc::autorelease::autoreleasepool::hff0bb51e136aa3b7
                               at /Users/adelalharbi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/rc/autorelease.rs:29:5
  75:        0x1044d50a8 - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::h051db54aef45a29d
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform_impl/macos/event_loop.rs:212:25
  76:        0x1044fbae0 - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::hd036c6f6df6c15a7
                               at /Users/adelalharbi/.cargo/git/checkouts/winit-57d3141eaf559308/9404575/src/platform/run_return.rs:62:9
  77:        0x10446808c - iced_winit::application::platform::run::hbcb7aabb290363db
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/winit/src/application.rs:880:17
  78:        0x104466c14 - iced_winit::application::run::h97277b8c6471f09b
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/winit/src/application.rs:222:5
  79:        0x10446c5a4 - iced::application::Application::run::h72379819a6e7ae88
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/src/application.rs:208:12
  80:        0x10446c7f8 - iced::sandbox::Sandbox::run::heb6823f45a48ed89
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/src/sandbox.rs:153:9
  81:        0x1044c2130 - tour::main::h1ac84bf99f43444a
                               at /Users/adelalharbi/Projects/Rust/proj02/iced/examples/tour/src/main.rs:13:5
  82:        0x1044e6264 - core::ops::function::FnOnce::call_once::h552cc4dafb9261cf
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/ops/function.rs:250:5
  83:        0x1044fe7bc - std::sys_common::backtrace::__rust_begin_short_backtrace::hdb9564d771f69e02
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/sys_common/backtrace.rs:134:18
  84:        0x104468050 - std::rt::lang_start::{{closure}}::hf7784b917b44c0b1
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/rt.rs:166:18
  85:        0x1051cacd0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2cc11bf729edeca2
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/core/src/ops/function.rs:287:13
  86:        0x1051cacd0 - std::panicking::try::do_call::h3ab7025776422c26
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:487:40
  87:        0x1051cacd0 - std::panicking::try::h814b73f9c767aedd
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:451:19
  88:        0x1051cacd0 - std::panic::catch_unwind::h6d8e31b76fdfb09d
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panic.rs:140:14
  89:        0x1051cacd0 - std::rt::lang_start_internal::{{closure}}::hbed70f5d0a3ec506
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/rt.rs:148:48
  90:        0x1051cacd0 - std::panicking::try::do_call::h6b9b8103146db6ec
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:487:40
  91:        0x1051cacd0 - std::panicking::try::h38bcf716aeda61f1
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panicking.rs:451:19
  92:        0x1051cacd0 - std::panic::catch_unwind::h0758195f3a8d9aac
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/panic.rs:140:14
  93:        0x1051cacd0 - std::rt::lang_start_internal::h1134bf8442075913
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/rt.rs:148:20
  94:        0x104468014 - std::rt::lang_start::h707ec2ba11bdf791
                               at /rustc/db0cbc48d4aaa300713a95d9b317a365a474490c/library/std/src/rt.rs:165:17
  95:        0x1044c6434 - _main
```

**Comment by 13r0ck** [comment]
This is an upstream bug. Fixed [here](https://github.com/pop-os/cosmic-text/pull/118). Will iced and other dependents to pull in the new version, but the advanced-text branch isn't released yet. So that is fine

**Comment by adals** [comment]
thanks. should close it
