### ISSUE TITLE
Panic on startup 

### ISSUE THREAD

**Issue by IohannRabeson** [iced-rs/iced#1792]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Hi! Since I updated to Iced 0.9, my application panics  on Windows only with the message:
```
thread 'main' panicked at 'Error in Surface::configure: Both `Surface` width and height must be non-zero. Wait to recreate the `Surface` until the window has non-zero area.', C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:316:9
```

I can confirm on my Mac I do not reproduce this issue.

### What is the expected behavior?

I expect the program does not panic

### Version

master

### Operative System

Windows

### Do you have any log output?

```shell
thread 'main' panicked at 'Error in Surface::configure: Both `Surface` width and height must be non-zero. Wait to recreate the `Surface` until the window has non-zero area.', C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:316:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: wgpu::backend::direct::Context::handle_error_fatal<enum2$<wgpu_core::present::ConfigureSurfaceError> >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:316
   3: wgpu::backend::direct::impl$7::surface_configure
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:742
   4: wgpu::context::impl$5::surface_configure<wgpu::backend::direct::Context>
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\context.rs:2053
   5: wgpu::Surface::configure
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\lib.rs:4113
   6: iced_wgpu::window::compositor::impl$1::configure_surface<enum2$<iced_style::theme::Theme> >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_wgpu-0.10.0\src\window\compositor.rs:174
   7: iced_winit::application::run_instance::async_fn$0<iced::application::Instance<teamwork_launcher::application::TeamworkLauncher>,tokio::runtime::runtime::Runtime,iced_wgpu::window::compositor::Compositor<enum2$<iced_style::theme::Theme> > >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.9.1\src\application.rs:302
   8: iced_winit::application::run::closure$1<iced::application::Instance<teamwork_launcher::application::TeamworkLauncher>,tokio::runtime::runtime::Runtime,iced_wgpu::window::compositor::Compositor<enum2$<iced_style::theme::Theme> > >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.9.1\src\application.rs:251
   9: winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<enum2$<teamwork_launcher::application::message::Message>,iced_winit::application::run::closure_env$1<iced::application::Instance<teamwork_launcher::application::TeamworkLauncher>,to
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:254
  10: alloc::boxed::impl$46::call_mut<tuple$<enum2$<winit::event::Event<enum2$<teamwork_launcher::application::message::Message> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<enum2$<tea
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\alloc\src\boxed.rs:1995
  11: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum2$<teamwork_launcher::application::message::Message> >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:250
  12: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<teamwork_launcher::application::message::Message> > >
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\panic\unwind_safe.rs:271
  13: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<teamwork_launcher::application::message::Message> > >,tuple$<> >
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\std\src\panicking.rs:483
  14: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$1<tokio::runtime::blocking::task::BlockingTask<tokio::fs::write::write::async_fn$0::closure_env$0<ref$<std::path::PathBuf>,byt
  15: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<teamwork_launcher::application::message::Message> > > >
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\std\src\panicking.rs:447
  16: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<teamwork_launcher::application::message::Message> > >,tuple$<> >
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\std\src\panic.rs:140
  17: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<teamwork_launcher::application::message::Message> >::catch_unwind<enum2$<teamwork_launcher::application::message::Message>,tuple$<>,winit::platform_impl::platform::event_loop::runn
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:157
  18: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<teamwork_launcher::application::message::Message> >::call_event_handler<enum2$<teamwork_launcher::application::message::Message> >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:242
  19: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<teamwork_launcher::application::message::Message> >::call_new_events<enum2$<teamwork_launcher::application::message::Message> >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:398
  20: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<teamwork_launcher::application::message::Message> >::move_state_to<enum2$<teamwork_launcher::application::message::Message> >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:312
  21: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<teamwork_launcher::application::message::Message> >::poll<enum2$<teamwork_launcher::application::message::Message> >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:206
  22: winit::platform_impl::platform::event_loop::EventLoop<enum2$<teamwork_launcher::application::message::Message> >::run_return<enum2$<teamwork_launcher::application::message::Message>,iced_winit::application::run::closure_env$1<iced::application::Instance<t
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:263
  23: winit::platform::run_return::impl$0::run_return<enum2$<teamwork_launcher::application::message::Message>,iced_winit::application::run::closure_env$1<iced::application::Instance<teamwork_launcher::application::TeamworkLauncher>,tokio::runtime::runtime::Run
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform\run_return.rs:62
  24: iced_winit::application::platform::run<enum2$<teamwork_launcher::application::message::Message>,iced_winit::application::run::closure_env$1<iced::application::Instance<teamwork_launcher::application::TeamworkLauncher>,tokio::runtime::runtime::Runtime,iced
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.9.1\src\application.rs:870
  25: iced_winit::application::run<iced::application::Instance<teamwork_launcher::application::TeamworkLauncher>,tokio::runtime::runtime::Runtime,iced_wgpu::window::compositor::Compositor<enum2$<iced_style::theme::Theme> > >
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.9.1\src\application.rs:226
  26: iced::application::Application::run<teamwork_launcher::application::TeamworkLauncher>
             at C:\Users\iohan\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-0.9.0\src\application.rs:209
  27: teamwork_launcher::main
             at .\teamwork-launcher\src\main.rs:39
  28: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<iced::error::Error> > > (*)(),tuple$<> >
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by IohannRabeson** [comment]
Ok, my bad. For some reason the application was starting with a window with width and height set to 0..
