### ISSUE TITLE
Widget helper function `scrollable( content )` panics at `tree.rs` ` fn downcast_ref<T>(&self) -> &T`

### ISSUE THREAD

**Issue by rizzen-yazston** [iced-rs/iced#2178]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

thread 'main' panicked at /home/*******/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/core/src/widget/tree.rs:254:28:
Downcast on stateless state

### What is the expected behavior?

To have a valid `State`.

### Version

master

### Operating System

Linux

### Do you have any log output?

```shell
stack backtrace:
   0:     0x55fd4ba6f4dc - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fd4ba6f4dc - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fd4ba6f4dc - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55fd4ba6f4dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fd4ba9d55c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x55fd4ba9d55c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x55fd4ba6b73e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x55fd4ba6f2c4 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fd4ba6f2c4 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fd4ba70973 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x55fd4ba7068c - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x55fd4ba70ef9 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x55fd4ba70db1 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13
  13:     0x55fd4ba6fa06 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55fd4ba70b42 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x55fd4a1811d3 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x55fd4a2990e6 - iced_core::widget::tree::State::downcast_mut::ha0dd97fea68c5171
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/core/src/widget/tree.rs:254:28
  17:     0x55fd4a2de6c4 - <iced_widget::scrollable::Scrollable<Message,Renderer> as iced_core::widget::Widget<Message,Renderer>>::on_event::h901c925a912a618d
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/widget/src/scrollable.rs:301:13
  18:     0x55fd4a30a7d7 - <********::widget::event_control::Container<Message,Renderer> as iced_core::widget::Widget<Message,Renderer>>::on_event::h802ed718caaea0f1
                               at /home/********/data/projects/github/********/crates/lib/src/widget/event_control.rs:223:9
  19:     0x55fd4a273501 - iced_runtime::user_interface::UserInterface<Message,Renderer>::update::{{closure}}::ha6af115dabad24c3
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/runtime/src/user_interface.rs:313:36
  20:     0x55fd4a237d0a - core::iter::adapters::map::map_fold::{{closure}}::h1457481a1ebd57d0
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:84:28
  21:     0x55fd4a1c64c0 - core::iter::traits::iterator::Iterator::fold::h58ee3aedb2484557
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2639:21
  22:     0x55fd4a236902 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h669f7d3e461a9329
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:124:9
  23:     0x55fd4a237bf6 - core::iter::traits::iterator::Iterator::for_each::h846f15a9d87e88f7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:857:9
  24:     0x55fd4a25f41f - alloc::vec::Vec<T,A>::extend_trusted::h7efaf1608bca5d46
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/mod.rs:2828:17
  25:     0x55fd4a26387a - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::h11c1d7fe2721b985
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/spec_extend.rs:26:9
  26:     0x55fd4a25d107 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h60d1154ee737fc76
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  27:     0x55fd4a26394d - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hb2c918d7327ff6c6
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/spec_from_iter.rs:33:9
  28:     0x55fd4a26375a - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h3c3c0225d422583f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/mod.rs:2696:9
  29:     0x55fd4a23788d - core::iter::traits::iterator::Iterator::collect::hb039185138ab06fb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/traits/iterator.rs:2053:9
  30:     0x55fd4a27313b - iced_runtime::user_interface::UserInterface<Message,Renderer>::update::hdc3392f9b489c37a
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/runtime/src/user_interface.rs:302:30
  31:     0x55fd4a26bd1a - iced_winit::multi_window::run_instance::{{closure}}::h2ca399f113869f0b
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/winit/src/multi_window.rs:454:56
  32:     0x55fd4a26f216 - iced_winit::multi_window::run::{{closure}}::hd356cc06c6eaf602
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/winit/src/multi_window.rs:241:28
  33:     0x55fd4a1c8651 - winit::platform_impl::platform::sticky_exit_callback::h32f14c5c3f85ab4f
                               at /home/********/.cargo/git/checkouts/winit-57d3141eaf559308/c52db20/src/platform_impl/linux/mod.rs:884:9
  34:     0x55fd4a1e0ce6 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::h83e8b24905e018c8
                               at /home/********/.cargo/git/checkouts/winit-57d3141eaf559308/c52db20/src/platform_impl/linux/x11/mod.rs:358:17
  35:     0x55fd4a1e1926 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h74463624e2bb6d78
                               at /home/********/.cargo/git/checkouts/winit-57d3141eaf559308/c52db20/src/platform_impl/linux/x11/mod.rs:483:27
  36:     0x55fd4a1c79a6 - winit::platform_impl::platform::EventLoop<T>::run_return::h5e7296e42768ea02
                               at /home/********/.cargo/git/checkouts/winit-57d3141eaf559308/c52db20/src/platform_impl/linux/mod.rs:785:56
  37:     0x55fd4a2668da - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::h60fd6716f3e03a33
                               at /home/********/.cargo/git/checkouts/winit-57d3141eaf559308/c52db20/src/platform/run_return.rs:51:9
  38:     0x55fd4a26676d - iced_winit::multi_window::platform::run::h0d22ae88354a15e6
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/winit/src/multi_window.rs:1190:17
  39:     0x55fd4a26e96d - iced_winit::multi_window::run::he8cf171ef9eef6b3
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/winit/src/multi_window.rs:213:5
  40:     0x55fd4a2437c8 - iced::multi_window::application::Application::run::hd555376e1252e460
                               at /home/********/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fc285d3/src/multi_window/application.rs:185:12
  41:     0x55fd4a270f7e - request_tracker::main::h783caa76889a6dc4
                               at /home/********/data/projects/github/********/crates/bin/src/main.rs:86:5
  42:     0x55fd4a1cdf02 - core::ops::function::FnOnce::call_once::hc9efe31667490e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  43:     0x55fd4a23dd6d - std::sys_common::backtrace::__rust_begin_short_backtrace::hd0d7857593c51f4f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:154:18
  44:     0x55fd4a186f56 - std::rt::lang_start::{{closure}}::h6502e469aad0658c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:166:18
  45:     0x55fd4ba64b4b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc4f8a3f5ada78c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  46:     0x55fd4ba64b4b - std::panicking::try::do_call::he5f117a9e13dadde
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  47:     0x55fd4ba64b4b - std::panicking::try::h2f3af9afce3a0443
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  48:     0x55fd4ba64b4b - std::panic::catch_unwind::h6d6c387f38ef05ea
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  49:     0x55fd4ba64b4b - std::rt::lang_start_internal::{{closure}}::h6ca09d5905711415
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  50:     0x55fd4ba64b4b - std::panicking::try::do_call::ha9fd18ea06654a4b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  51:     0x55fd4ba64b4b - std::panicking::try::hda5c2a4432362341
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  52:     0x55fd4ba64b4b - std::panic::catch_unwind::h440f731b142bc235
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  53:     0x55fd4ba64b4b - std::rt::lang_start_internal::hc0b4e50f058f62ce
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  54:     0x55fd4a186f2a - std::rt::lang_start::h8de90b36875da780
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:165:17
  55:     0x55fd4a2710de - main
  56:     0x7f64e504f2bd - __libc_start_main
  57:     0x55fd4a18198a - _start
                               at /home/abuild/rpmbuild/BUILD/glibc-2.31/csu/../sysdeps/x86_64/start.S:120
  58:                0x0 - <unknown>
```

**Comment by hecrj** [comment]
SSCCE please!

**Comment by rizzen-yazston** [comment]
Just copied `widget::Container` and made changes as recommended by Night Hunter (on discord):

field `events_enabled: bool,` to the `Container`,

with added parameter to the `new()` function to set the boolean state,

and finally added at the start of `fn on_event()` method these 3 lines:

```
if !self.events_enabled {
    return event::Status::Ignored;
}
```
