### ISSUE TITLE
Crash on raspberry pi when using

### ISSUE THREAD

**Issue by spamviech** [iced-rs/iced#2337]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Running the following app on a rasperry pi crashes, when the "wgpu"-feature is enabled.
The error message is a "unwrap on a None-value" in wgpu-core (see below).
This was not an issue with iced v0.10.
In case it is relevant:
- the app was cross-compiled on a windows-machine using cross
- the rapberry-pi is running default 64bit raspbian image

```rust
use iced::{Application, Settings};

struct Dummy;

impl Application for Dummy {
    type Executor = iced::executor::Default;
    type Flags = ();
    type Message = ();
    type Theme = iced::Theme;

    fn new((): Self::Flags) -> (Self, iced::Command<Self::Message>) {
        (Dummy, iced::Command::none())
    }

    fn title(&self) -> String {
        String::from("Dummy")
    }

    fn update(&mut self, (): Self::Message) -> iced::Command<Self::Message> {
        iced::Command::none()
    }

    fn view(&self) -> iced::Element<'_, Self::Message, Self::Theme, iced::Renderer> {
        iced::widget::Text::new("Test").into()
    }
}

fn main() -> iced::Result {
    Dummy::run(Settings::default())
}
```

Note: This reads similar to https://github.com/iced-rs/iced/issues/2314
I decided to open a new issue, because the error message is different.

### What is the expected behavior?

No crash, a window with the text "Test" is shown.

### Version

crates.io release

### Operating System

Linux

### Do you have any log output?

```shell
$ RUST_BACKTRACE=full ~/bin/zugkontrolle-5.0.0-aarch64-unknown-linux-gnu
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_winit-0.12.2/src/application.rs:119:10:
Create event loop: Os(OsError { line: 786, file: "/cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs", error: Misc("neither WAYLAND_DISPLAY nor WAYLAND_SOCKET nor DISPLAY is set.") })
stack backtrace:
   0:       0x558aa24778 - <unknown>
   1:       0x558a88208c - <unknown>
   2:       0x558a9fa1bc - <unknown>
   3:       0x558aa25ec0 - <unknown>
   4:       0x558aa256c0 - <unknown>
   5:       0x558aa26720 - <unknown>
   6:       0x558aa261d0 - <unknown>
   7:       0x558aa26138 - <unknown>
   8:       0x558aa26130 - <unknown>
   9:       0x558a822d94 - <unknown>
  10:       0x558a8230d4 - <unknown>
  11:       0x558ad1f4c0 - <unknown>
  12:       0x558ad82178 - <unknown>
  13:       0x558ad6a104 - <unknown>
  14:       0x558ad81e2c - <unknown>
  15:       0x7fa38e8e18 - __libc_start_main
                               at ./csu/../csu/libc-start.c:308:16
  16:       0x558a85098c - <unknown>
Abgebrochen
```

**Comment by n1ght-hunter** [comment]
probably a issue with wgpu not iced
https://github.com/gfx-rs/wgpu/blob/9f505e730fa4ef62c040aa3f67e730ab2059a1cf/wgpu-core/src/instance.rs#L521
like to the code in wgpu

**Comment by Krahos** [comment]
I got what looks like the same issue. Attaching the stacktrace in case it would be useful to someone
```
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/panicking.rs:692:5
   1: core::panicking::panic_fmt
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/panicking.rs:145:5
   3: core::option::unwrap_failed
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/option.rs:2015:5
   4: core::option::Option<T>::unwrap
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/option.rs:978:21
   5: wgpu_core::instance::<impl wgpu_core::global::Global<G>>::instance_create_surface
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-core-0.19.4/src/instance.rs:521:27
   6: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::instance_create_surface
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-0.19.4/src/backend/wgpu_core.rs:529:17
   7: <T as wgpu::context::DynContext>::instance_create_surface
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-0.19.4/src/context.rs:1995:40
   8: wgpu::Instance::create_surface_unsafe
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-0.19.4/src/lib.rs:2052:35
   9: wgpu::Instance::create_surface
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-0.19.4/src/lib.rs:1985:31
  10: iced_wgpu::window::compositor::Compositor::request::{{closure}}::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced_wgpu-0.13.5/src/window/compositor.rs:76:32
  11: core::option::Option<T>::and_then
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/option.rs:1452:24
  12: iced_wgpu::window::compositor::Compositor::request::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced_wgpu-0.13.5/src/window/compositor.rs:75:34
  13: iced_wgpu::window::compositor::new::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced_wgpu-0.13.5/src/window/compositor.rs:206:60
  14: <iced_wgpu::window::compositor::Compositor as iced_graphics::compositor::Compositor>::with_backend::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced_wgpu-0.13.5/src/window/compositor.rs:285:53
  15: <iced_renderer::fallback::Compositor<A,B> as iced_graphics::compositor::Compositor>::with_backend::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced_renderer-0.13.0/src/fallback.rs:245:18
  16: <iced_winit::program::run::Runner<Message,F,C> as winit::application::ApplicationHandler<iced_runtime::Action<Message>>>::resumed::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced_winit-0.13.0/src/program.rs:326:63
  17: futures_executor::local_pool::block_on::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-executor-0.3.31/src/local_pool.rs:316:23
  18: futures_executor::local_pool::run_executor::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-executor-0.3.31/src/local_pool.rs:90:37
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/thread/local.rs:308:12
  20: std::thread::local::LocalKey<T>::with
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/thread/local.rs:272:9
  21: futures_executor::local_pool::run_executor
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-executor-0.3.31/src/local_pool.rs:86:5
  22: futures_executor::local_pool::block_on
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-executor-0.3.31/src/local_pool.rs:316:5
  23: <iced_winit::program::run::Runner<Message,F,C> as winit::application::ApplicationHandler<iced_runtime::Action<Message>>>::resumed
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced_winit-0.13.0/src/program.rs:342:17
  24: winit::event_loop::dispatch_event_for_app
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/event_loop.rs:646:27
  25: winit::event_loop::EventLoop<T>::run_app::{{closure}}
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/event_loop.rs:265:49
  26: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/ops/function.rs:294:13
  27: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::single_iteration
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/platform_impl/linux/wayland/event_loop/mod.rs:317:13
  28: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::pump_events
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/platform_impl/linux/wayland/event_loop/mod.rs:211:13
  29: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::run_on_demand
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/platform_impl/linux/wayland/event_loop/mod.rs:181:19
  30: winit::platform_impl::linux::EventLoop<T>::run_on_demand
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/platform_impl/linux/mod.rs:819:56
  31: winit::platform_impl::linux::EventLoop<T>::run
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/platform_impl/linux/mod.rs:812:9
  32: winit::event_loop::EventLoop<T>::run_app
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.9/src/event_loop.rs:265:9
  33: iced_winit::program::run
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced_winit-0.13.0/src/program.rs:605:17
  34: iced::program::Program::run_with
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced-0.13.1/src/program.rs:177:12
  35: iced::program::Program::run
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced-0.13.1/src/program.rs:81:9
  36: iced::application::Application<P>::run
             at /home/seb/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/iced-0.13.1/src/application.rs:167:9
  37: planter::main
             at ./src/main.rs:6:5
  38: core::ops::function::FnOnce::call_once
             at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/core/src/ops/function.rs:250:5
```

However, it looks like a wgpu issue, as mentioned above.
