### ISSUE TITLE
Panic location should be exposed

### ISSUE THREAD

**Issue by Tahinli** [iced-rs/iced#2511]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

My code is not working in debug mode because of an error, I've already fixed that I was using length::fill for scrollable and I changed it to exact value, this is not my question.

Problem is I think you forgot to expose to error to outer code where it causes instead of internal crate.

<img width="620" alt="image" src="https://github.com/user-attachments/assets/b16b915e-1212-43ed-96de-c1a70de8f212">

### What is the expected behavior?

Error should be seen in my code not in your internal code.

### Version

master

### Operating System

Linux

### Do you have any log output?

```shell
---BACKTRACE---
Hello, world!
thread 'main' panicked at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/widget/src/scrollable.rs:62:9:
scrollable content must not fill its vertical scrolling axis
stack backtrace:
   0:     0x55fdacfef435 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x55fdacfef435 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fdacfef435 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55fdacfef435 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fdad01c0bb - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:     0x55fdad01c0bb - core::fmt::write::hc090a2ffd6b28c4a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:     0x55fdacfeb1bf - std::io::Write::write_fmt::h8898bac6ff039a23
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:     0x55fdacfef20e - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fdacfef20e - std::sys_common::backtrace::print::ha96650907276675e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fdacff04c9 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
  10:     0x55fdacff020d - std::panicking::default_hook::h207342be97478370
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
  11:     0x55fdacff0963 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:795:13
  12:     0x55fdacff080b - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:656:13
  13:     0x55fdacfef8f9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55fdacff0577 - rust_begin_unwind
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
  15:     0x55fdaad80d13 - core::panicking::panic_fmt::hdc63834ffaaefae5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  16:     0x55fdaaef6afc - iced_widget::scrollable::Scrollable<Message,Theme,Renderer>::with_direction::h67fe90e8618a87fa
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/widget/src/scrollable.rs:62:9
  17:     0x55fdaaef6e4d - iced_widget::scrollable::Scrollable<Message,Theme,Renderer>::new::h3401262fd6183fc4
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/widget/src/scrollable.rs:52:9
  18:     0x55fdab049b2e - iced_widget::helpers::scrollable::hed4574798e193802
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/widget/src/helpers.rs:568:5
  19:     0x55fdaaf22b8e - streamer::gui::Streamer::view::h2ab9299b29764f05
                               at /home/tahinli/Documents/Code/Rust/radioxide/streamer/src/gui.rs:732:33
  20:     0x55fdaade3a10 - core::ops::function::Fn::call::hc7bed1469b3de57f
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:79:5
  21:     0x55fdaae38d25 - <T as iced::program::View<State,Message,Theme,Renderer>>::view::h30110025846a0163
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:872:9
  22:     0x55fdaae331c9 - <iced::program::program::Application<State,Message,Theme,Renderer,Update,View> as iced::program::Definition>::view::h6c3697a817481636
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:125:13
  23:     0x55fdaae34847 - <iced::program::with_title::WithTitle<P,Title> as iced::program::Definition>::view::hb5e7fc15bbe2cfdf
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:507:13
  24:     0x55fdaae34673 - <iced::program::with_load::WithLoad<P,F> as iced::program::Definition>::view::hab591a5e22e4588b
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:568:13
  25:     0x55fdaae34693 - <iced::program::with_load::WithLoad<P,F> as iced::program::Definition>::view::hd460737e807b8c3e
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:568:13
  26:     0x55fdaae32e33 - <iced::program::with_subscription::WithSubscription<P,F> as iced::program::Definition>::view::h0c44994c9a9a0361
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:640:13
  27:     0x55fdaae330a7 - <iced::program::Program<P>::run_with::Instance<P,I> as iced::application::Application>::view::hc607221e59932140
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:229:17
  28:     0x55fdaad8c33a - <iced::application::Instance<A> as iced_runtime::program::Program>::view::h4ccc0adddb361c46
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/application.rs:242:9
  29:     0x55fdaada0fb9 - iced_winit::application::build_user_interface::h26159a57951bd301
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/winit/src/application.rs:842:16
  30:     0x55fdaad9ec0c - iced_winit::application::run_instance::{{closure}}::hfc9777e8edfde448
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/winit/src/application.rs:549:48
  31:     0x55fdaada2797 - iced_winit::application::run::Runner<Message,F,C>::process_event::h9920be94ddf89932
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/winit/src/application.rs:441:24
  32:     0x55fdaada2ea2 - <iced_winit::application::run::Runner<Message,F,C> as winit::application::ApplicationHandler<Message>>::window_event::ha4b9cebe29015d3a
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/winit/src/application.rs:372:13
  33:     0x55fdaae53040 - winit::event_loop::dispatch_event_for_app::h88491b9876082daf
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/event_loop.rs:628:52
  34:     0x55fdaae53040 - winit::event_loop::EventLoop<T>::run_app::{{closure}}::h6d7213b60d66b6d6
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/event_loop.rs:262:49
  35:     0x55fdaae52ddf - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h98d5f1b97686e05b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:294:13
  36:     0x55fdaae18753 - winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}::h9df67018f239d5f5
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/platform_impl/linux/x11/mod.rs:595:21
  37:     0x55fdaadb8849 - winit::platform_impl::platform::x11::event_processor::EventProcessor::process_event::h248ee6160eacb74e
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/platform_impl/linux/x11/event_processor.rs:124:13
  38:     0x55fdaae182ec - winit::platform_impl::platform::x11::EventLoop<T>::drain_events::h083c73894ae0ec69
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/platform_impl/linux/x11/mod.rs:586:13
  39:     0x55fdaae19a4b - winit::platform_impl::platform::x11::EventLoop<T>::single_iteration::hdf80086b019637c3
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/platform_impl/linux/x11/mod.rs:522:9
  40:     0x55fdaae17f96 - winit::platform_impl::platform::x11::EventLoop<T>::pump_events::h43479da5f581f36b
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/platform_impl/linux/x11/mod.rs:420:13
  41:     0x55fdaae1891c - winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand::hf2a396a3abca610b
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/platform_impl/linux/x11/mod.rs:387:19
  42:     0x55fdaae51366 - winit::platform_impl::platform::EventLoop<T>::run_on_demand::hefd578d642fb7174
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/platform_impl/linux/mod.rs:803:56
  43:     0x55fdaae51bca - winit::platform_impl::platform::EventLoop<T>::run::h00acc8f07cb1db8f
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/platform_impl/linux/mod.rs:796:9
  44:     0x55fdaae52f2f - winit::event_loop::EventLoop<T>::run_app::h213b4bfaefee1fd7
                               at /home/tahinli/.cargo/git/checkouts/winit-57d3141eaf559308/8affa52/src/event_loop.rs:262:9
  45:     0x55fdaada2136 - iced_winit::application::run::h12f3766eaa37fff7
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/winit/src/application.rs:459:17
  46:     0x55fdaae333af - iced::application::Application::run::h8a4e1d5fa07accc3
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/application.rs:215:12
  47:     0x55fdaae34327 - iced::program::Program<P>::run_with::h2ec81f3312854913
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:247:9
  48:     0x55fdaae33bdd - iced::program::Program<P>::run::hbe998f40f64fc1db
                               at /home/tahinli/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/fb23e4c/src/program.rs:171:9
  49:     0x55fdaaeb7198 - streamer::main::{{closure}}::{{closure}}::h22a260e5fb0ce65b
                               at /home/tahinli/Documents/Code/Rust/radioxide/streamer/src/main.rs:7:9
  50:     0x55fdaae312bf - tokio::runtime::context::runtime_mt::exit_runtime::h3df0aa9c2ca7a991
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime_mt.rs:35:5
  51:     0x55fdaae21797 - tokio::runtime::scheduler::multi_thread::worker::block_in_place::h2c7e9ac46b41797f
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:438:9
  52:     0x55fdaae176e6 - tokio::runtime::scheduler::block_in_place::block_in_place::hbf5816d1535e3aee
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/block_in_place.rs:20:5
  53:     0x55fdaaeb6f16 - tokio::task::blocking::block_in_place::h6312790975e5d57c
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/blocking.rs:78:9
  54:     0x55fdaaeb7055 - streamer::main::{{closure}}::h2cd05cf2267ee9e6
                               at /home/tahinli/Documents/Code/Rust/radioxide/streamer/src/main.rs:6:5
  55:     0x55fdaadb29b4 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h02dfaf45e789bb9b
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/park.rs:281:63
  56:     0x55fdaadb2826 - tokio::runtime::coop::with_budget::h15a985d91485a8ff
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  57:     0x55fdaadb2826 - tokio::runtime::coop::budget::h7715eb30c96283fc
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  58:     0x55fdaadb2826 - tokio::runtime::park::CachedParkThread::block_on::h3ed8b91215c9ad5b
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/park.rs:281:31
  59:     0x55fdaadff66a - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h030b4ab5d4fbf19c
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/blocking.rs:66:9
  60:     0x55fdaae156bb - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h47cd11ef5bdc373c
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  61:     0x55fdaae3d0ca - tokio::runtime::context::runtime::enter_runtime::h75b240ab9258c091
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  62:     0x55fdaae1566d - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hc5678af75ea33aa3
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  63:     0x55fdaaeb24f8 - tokio::runtime::runtime::Runtime::block_on::h0618bd35b12ada33
                               at /home/tahinli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/runtime.rs:351:45
  64:     0x55fdaad9bb4c - streamer::main::h1fe977d692bcde74
                               at /home/tahinli/Documents/Code/Rust/radioxide/streamer/src/main.rs:6:5
  65:     0x55fdaade411b - core::ops::function::FnOnce::call_once::h199c4cee3c9f6bea
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  66:     0x55fdaadfb19e - std::sys_common::backtrace::__rust_begin_short_backtrace::h437d110b67276ca8
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
  67:     0x55fdaae31531 - std::rt::lang_start::{{closure}}::h4752135c78b519de
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
  68:     0x55fdacfe5b30 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6abeee5a7794ceb5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:284:13
  69:     0x55fdacfe5b30 - std::panicking::try::do_call::hd6e966bb06877057
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  70:     0x55fdacfe5b30 - std::panicking::try::hc9b3807f5768cb19
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  71:     0x55fdacfe5b30 - std::panic::catch_unwind::h94a757c154076c6e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  72:     0x55fdacfe5b30 - std::rt::lang_start_internal::{{closure}}::hc5223fb36050c743
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:48
  73:     0x55fdacfe5b30 - std::panicking::try::do_call::hddf7b4e1ebeb3f69
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  74:     0x55fdacfe5b30 - std::panicking::try::h1842860a1f941a31
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  75:     0x55fdacfe5b30 - std::panic::catch_unwind::h009016ccf811d4c3
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  76:     0x55fdacfe5b30 - std::rt::lang_start_internal::h3ed4fe7b2f419135
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:20
  77:     0x55fdaae3150a - std::rt::lang_start::ha65e1bad46d7c810
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
  78:     0x55fdaad9bbee - main
  79:     0x7f799fdee088 - __libc_start_call_main
  80:     0x7f799fdee14b - __libc_start_main_impl
  81:     0x55fdaad81805 - _start
  82:                0x0 - <unknown>
```

**Comment by JL710** [comment]
What are you putting in your scrollable?

**Comment by hecrj** [comment]
It's right there.

```
   19:     0x55fdaaf22b8e - streamer::gui::Streamer::view::h2ab9299b29764f05
                               at /home/tahinli/Documents/Code/Rust/radioxide/streamer/src/gui.rs:732:33
```

**Comment by Tahinli** [comment]
> What are you putting in your scrollable?

Buttons.

**Comment by Tahinli** [comment]
> It's right there.
> 
> ```
>    19:     0x55fdaaf22b8e - streamer::gui::Streamer::view::h2ab9299b29764f05
>                                at /home/tahinli/Documents/Code/Rust/radioxide/streamer/src/gui.rs:732:33
> ```

You know what I meant, I've already fixed like I said. But error should be seen in my code in the first place not in crate itself. Afaik it's done by #[track_caller].
