### ISSUE TITLE
`window::screenshot` crashes when window is minimized

### ISSUE THREAD

**Issue by rscarson** [iced-rs/iced#2648]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Calling `window::screenshot` while the target window is minimized causes a crash

```
thread 'main' panicked at C:\Users\rcarson1\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `iced_wgpu.offscreen.source_texture`
    Dimension X is zero
```

### What is the expected behavior?

Either an empty image, or an error, or simply not submitting the result task are all fine

### Version

crates.io release

### Operating System

Windows

### Do you have any log output?

```shell
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
   2: wgpu::backend::wgpu_core::default_error_handler
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\backend\wgpu_core.rs:3006
   3: core::ops::function::Fn::call<void (*)(enum2$<wgpu::Error>),tuple$<enum2$<wgpu::Error> > >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\ops\function.rs:79
   4: alloc::boxed::impl$50::call<tuple$<enum2$<wgpu::Error> >,dyn$<wgpu::UncapturedErrorHandler<assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\alloc\src\boxed.rs:2084
   5: wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\backend\wgpu_core.rs:2992
   6: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error<enum2$<wgpu_core::resource::CreateTextureError> >
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\backend\wgpu_core.rs:262
   7: wgpu::backend::wgpu_core::impl$7::device_create_texture
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\backend\wgpu_core.rs:1251
   8: wgpu::context::impl$5::device_create_texture<wgpu::backend::wgpu_core::ContextWgpuCore>
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\context.rs:2299
   9: wgpu::Device::create_texture
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\lib.rs:2532
  10: iced_wgpu::window::compositor::screenshot<alloc::string::String>
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_wgpu-0.13.5\src\window\compositor.rs:394
  11: iced_wgpu::window::compositor::impl$2::screenshot<alloc::string::String>
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_wgpu-0.13.5\src\window\compositor.rs:372
  12: iced_renderer::fallback::impl$5::screenshot<iced_wgpu::window::compositor::Compositor,iced_tiny_skia::window::compositor::Compositor,alloc::string::String>
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_renderer-0.13.0\src\fallback.rs:366
  13: iced_winit::program::run_action<iced::program::Program::run_with::Instance<iced::program::with_theme::WithTheme<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<zoneapp::app::A
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_winit-0.13.0\src\program.rs:1416
  14: iced_winit::program::run_instance::async_fn$0<iced::program::Program::run_with::Instance<iced::program::with_theme::WithTheme<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<z
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_winit-0.13.0\src\program.rs:753
  15: iced_winit::program::run::Runner<enum2$<zoneapp::app::event::ApplicationEvent>,enum2$<iced_winit::program::run_instance::async_fn_env$0<iced::program::Program::run_with::Instance<iced::program::with_theme::WithTheme<iced::program::with_subscription::WithSu
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_winit-0.13.0\src\program.rs:467
  16: iced_winit::program::run::impl$0::user_event<enum2$<zoneapp::app::event::ApplicationEvent>,enum2$<iced_winit::program::run_instance::async_fn_env$0<iced::program::Program::run_with::Instance<iced::program::with_theme::WithTheme<iced::program::with_subscrip
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_winit-0.13.0\src\program.rs:426
  17: winit::event_loop::dispatch_event_for_app
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\event_loop.rs:644
  18: winit::event_loop::impl$6::run_app::closure$0<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > >,iced_winit::program::run::Runner<enum2$<zoneapp::app::event::ApplicationEvent>,enum2$<iced_winit::program::run_instance::async_fn_en
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\event_loop.rs:265
  19: winit::platform_impl::windows::event_loop::impl$3::run_on_demand::closure$0<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > >,winit::event_loop::impl$6::run_app::closure_env$0<enum2$<iced_runtime::Action<enum2$<zoneapp::app::eve
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop.rs:253
  20: alloc::boxed::impl$49::call_mut<tuple$<enum2$<winit::event::Event<winit::platform_impl::windows::event_loop::UserEventPlaceholder> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<winit::platform_impl::windows::event_loop::UserEventPla
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\alloc\src\boxed.rs:2077
  21: winit::platform_impl::windows::event_loop::runner::impl$3::call_event_handler::closure$0<winit::platform_impl::windows::event_loop::UserEventPlaceholder>
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop\runner.rs:236
  22: core::panic::unwind_safe::impl$25::call_once<tuple$<>,winit::platform_impl::windows::event_loop::runner::impl$3::call_event_handler::closure_env$0<winit::platform_impl::windows::event_loop::UserEventPlaceholder> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\panic\unwind_safe.rs:272
  23: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::windows::event_loop::runner::impl$3::call_event_handler::closure_env$0<winit::platform_impl::windows::event_loop::UserEventPlaceholder> >,tuple$<> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\panicking.rs:557
  24: winit::platform_impl::windows::window_state::impl$26::eq
  25: std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\panicking.rs:521
  26: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::windows::event_loop::runner::impl$3::call_event_handler::closure_env$0<winit::platform_impl::windows::event_loop::UserEventPlaceholder> >,tuple$<> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\panic.rs:350
  27: winit::platform_impl::windows::event_loop::runner::EventLoopRunner<winit::platform_impl::windows::event_loop::UserEventPlaceholder>::catch_unwind<winit::platform_impl::windows::event_loop::UserEventPlaceholder,tuple$<>,winit::platform_impl::windows::event_
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop\runner.rs:173
  28: winit::platform_impl::windows::event_loop::runner::EventLoopRunner<winit::platform_impl::windows::event_loop::UserEventPlaceholder>::call_event_handler<winit::platform_impl::windows::event_loop::UserEventPlaceholder>
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop\runner.rs:230
  29: winit::platform_impl::windows::event_loop::runner::EventLoopRunner<winit::platform_impl::windows::event_loop::UserEventPlaceholder>::send_event<winit::platform_impl::windows::event_loop::UserEventPlaceholder>
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop\runner.rs:220
  30: winit::platform_impl::windows::event_loop::ThreadMsgTargetData::send_event
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop.rs:137
  31: winit::platform_impl::windows::event_loop::thread_event_target_callback::closure$0
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop.rs:2433
  32: core::ops::function::FnOnce::call_once<winit::platform_impl::windows::event_loop::thread_event_target_callback::closure_env$0,tuple$<> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\ops\function.rs:250
  33: core::panic::unwind_safe::impl$25::call_once<isize,winit::platform_impl::windows::event_loop::thread_event_target_callback::closure_env$0>
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\panic\unwind_safe.rs:272
  34: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::windows::event_loop::thread_event_target_callback::closure_env$0>,isize>
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\panicking.rs:557
  35: winit::platform_impl::windows::window_state::impl$26::eq
  36: std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\panicking.rs:521
  37: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::windows::event_loop::thread_event_target_callback::closure_env$0>,isize>
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\panic.rs:350
  38: winit::platform_impl::windows::event_loop::runner::EventLoopRunner<winit::platform_impl::windows::event_loop::UserEventPlaceholder>::catch_unwind<winit::platform_impl::windows::event_loop::UserEventPlaceholder,isize,winit::platform_impl::windows::event_loo
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop\runner.rs:173
  39: winit::platform_impl::windows::event_loop::thread_event_target_callback
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop.rs:2444
  40: CallWindowProcW
  41: DispatchMessageW
  42: winit::platform_impl::windows::event_loop::EventLoop<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > > >::wait_and_dispatch_message<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > > >
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop.rs:435
  43: winit::platform_impl::windows::event_loop::EventLoop<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > > >::run_on_demand<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > >,winit::event_loop::impl$6::run
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop.rs:259
  44: winit::platform_impl::windows::event_loop::EventLoop<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > > >::run<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > >,winit::event_loop::impl$6::run_app::clos
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\platform_impl\windows\event_loop.rs:222
  45: winit::event_loop::EventLoop<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > > >::run_app<enum2$<iced_runtime::Action<enum2$<zoneapp::app::event::ApplicationEvent> > >,iced_winit::program::run::Runner<enum2$<zoneapp::app::event:
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.30.5\src\event_loop.rs:265
  46: iced_winit::program::run<iced::program::Program::run_with::Instance<iced::program::with_theme::WithTheme<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<zoneapp::app::Applicat
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced_winit-0.13.0\src\program.rs:605
  47: iced::program::Program::run_with<iced::program::with_theme::WithTheme<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<zoneapp::app::Application,enum2$<zoneapp::app::event::App
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced-0.13.1\src\program.rs:177
  48: iced::application::Application<iced::program::with_theme::WithTheme<iced::program::with_subscription::WithSubscription<iced::program::with_title::WithTitle<iced::application::application::Instance<zoneapp::app::Application,enum2$<zoneapp::app::event::Appli
             at C:\Users\username\.cargo\registry\src\index.crates.io-6f17d22bba15001f\iced-0.13.1\src\application.rs:176
  49: zoneapp::app::Application::run
             at .\src\app.rs:97
  50: zoneapp::main
             at .\src\main.rs:37
  51: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<iced::error::Error> > > (*)(),tuple$<> >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\ops\function.rs:250
```

**Comment by kyteware** [comment]
This isn't reproducible on wayland, I can still take a screenshot when minimized.
