### ISSUE TITLE
panic when running example

### ISSUE THREAD

**Issue by CelestialCrafter** [iced-rs/iced#2694]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

i tried running the `tour` example (under x11) and it paniced with:

```
thread 'main' panicked at /home/celestial/Documents/projects/iced/winit/src/program.rs:192:10:
Create event loop: NotSupported(NotSupportedError)
```

### What is the expected behavior?

tour example to run

### Version

master

### Operating System

Linux

### Do you have any log output?

```shell
thread 'main' panicked at /home/celestial/Documents/projects/iced/winit/src/program.rs:192:10:
Create event loop: NotSupported(NotSupportedError)
stack backtrace:
   0:     0x55555771e346 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h9754a6437f1de22a
   1:     0x55555777c2db - core::fmt::write::hb706a393bb60a06f
   2:     0x555557726619 - std::io::Write::write_fmt::h9b447dc5d824d0bd
   3:     0x555557755056 - std::panicking::default_hook::{{closure}}::h227952daede9dd84
   4:     0x555557754ce6 - std::panicking::default_hook::h31626ee1feb8ee2a
   5:     0x5555577555b1 - std::panicking::rust_panic_with_hook::h76d2aa694a00748e
   6:     0x55555771e9a7 - std::panicking::begin_panic_handler::{{closure}}::h8855a344ffa1638b
   7:     0x55555771e559 - std::sys::backtrace::__rust_end_short_backtrace::h3110d0cbfbf26886
   8:     0x555557755194 - rust_begin_unwind
   9:     0x555555804293 - core::panicking::panic_fmt::h3af706d0346c1c60
  10:     0x555555803b06 - core::result::unwrap_failed::h2ba69a02b8a8418b
  11:     0x555555975657 - core::result::Result<T,E>::expect::h0f68b77700d9c22f
                               at /build/rustc-1.82.0-src/library/core/src/result.rs:1059:23
  12:     0x55555582e364 - iced_winit::program::run::hd7daffa9aa5748d4
                               at /home/celestial/Documents/projects/iced/winit/src/program.rs:190:22
  13:     0x55555584bbc2 - iced::program::Program::run_with::h6637245f70969289
                               at /home/celestial/Documents/projects/iced/src/program.rs:177:12
  14:     0x55555584b841 - iced::program::Program::run::h93227cf9becb0e0d
                               at /home/celestial/Documents/projects/iced/src/program.rs:81:9
  15:     0x5555558431db - iced::application::Application<P>::run::h1370f6abe8aed073
                               at /home/celestial/Documents/projects/iced/src/application.rs:167:9
  16:     0x5555558b9715 - tour::main::he9a548cf11250e23
                               at /home/celestial/Documents/projects/iced/examples/tour/src/main.rs:18:5
  17:     0x555555982cc2 - core::ops::function::FnOnce::call_once::hcd9ce90669450df3
                               at /build/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5
  18:     0x55555599fe75 - std::sys::backtrace::__rust_begin_short_backtrace::hbeeaeb635e4b9ca7
                               at /build/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:154:18
  19:     0x55555583fec6 - std::rt::lang_start::{{closure}}::h800cbb6b80eca175
                               at /build/rustc-1.82.0-src/library/std/src/rt.rs:164:18
  20:     0x555557757fd5 - std::rt::lang_start_internal::h2084fce485147f46
  21:     0x55555583fe9a - std::rt::lang_start::h02159a013bb7e04b
                               at /build/rustc-1.82.0-src/library/std/src/rt.rs:163:17
  22:     0x5555558be2ae - main
  23:     0x7ffff7ce327e - __libc_start_call_main
  24:     0x7ffff7ce3339 - __libc_start_main_alias_2
  25:     0x555555804855 - _start
  26:                0x0 - <unknown>
```

**Comment by CelestialCrafter** [comment]
it was set to :0
