### ISSUE TITLE
Canvas examples on MacOS failing to render

### ISSUE THREAD

**Issue by declanvk** [iced-rs/iced#427]
I'm still getting the issues with the canvas when compiling from master (038f75e) when antialiasing is turned on. I confirmed that turning off antialiasing shows the grid and other stuff.

Also on OSX 10.14.6.

<details>
<summary>See screenshot of game of life example</summary>

<img width="1280" alt="Screen Shot 2020-06-24 at 10 30 31 PM" src="https://user-images.githubusercontent.com/7276122/85660408-7097b300-b66a-11ea-8eb9-9019992c922c.png">

</details>

<details>
<summary>See `cargo tree -p game_of_life` output</summary>

```
game_of_life v0.1.0 (/Users/dev/Projects/xia/modules/iced/examples/game_of_life)
├── iced v0.1.1 (/Users/dev/Projects/xia/modules/iced)
│   ├── iced_core v0.2.1 (/Users/dev/Projects/xia/modules/iced/core)
│   ├── iced_futures v0.1.2 (/Users/dev/Projects/xia/modules/iced/futures)
│   │   ├── futures v0.3.5
│   │   │   ├── futures-channel v0.3.5
│   │   │   │   ├── futures-core v0.3.5
│   │   │   │   └── futures-sink v0.3.5
│   │   │   ├── futures-core v0.3.5
│   │   │   ├── futures-executor v0.3.5
│   │   │   │   ├── futures-core v0.3.5
│   │   │   │   ├── futures-task v0.3.5
│   │   │   │   │   └── once_cell v1.4.0
│   │   │   │   ├── futures-util v0.3.5
│   │   │   │   │   ├── futures-channel v0.3.5 (*)
│   │   │   │   │   ├── futures-core v0.3.5
│   │   │   │   │   ├── futures-io v0.3.5
│   │   │   │   │   ├── futures-macro v0.3.5
│   │   │   │   │   │   ├── proc-macro-hack v0.5.16
│   │   │   │   │   │   ├── proc-macro2 v1.0.18
│   │   │   │   │   │   │   └── unicode-xid v0.2.0
│   │   │   │   │   │   ├── quote v1.0.7
│   │   │   │   │   │   │   └── proc-macro2 v1.0.18 (*)
│   │   │   │   │   │   └── syn v1.0.31
│   │   │   │   │   │       ├── proc-macro2 v1.0.18 (*)
│   │   │   │   │   │       ├── quote v1.0.7 (*)
│   │   │   │   │   │       └── unicode-xid v0.2.0
│   │   │   │   │   ├── futures-sink v0.3.5
│   │   │   │   │   ├── futures-task v0.3.5 (*)
│   │   │   │   │   ├── memchr v2.3.3
│   │   │   │   │   ├── pin-project v0.4.22
│   │   │   │   │   │   └── pin-project-internal v0.4.22
│   │   │   │   │   │       ├── proc-macro2 v1.0.18 (*)
│   │   │   │   │   │       ├── quote v1.0.7 (*)
│   │   │   │   │   │       └── syn v1.0.31 (*)
│   │   │   │   │   ├── pin-utils v0.1.0
│   │   │   │   │   ├── proc-macro-hack v0.5.16
│   │   │   │   │   ├── proc-macro-nested v0.1.6
│   │   │   │   │   └── slab v0.4.2
│   │   │   │   └── num_cpus v1.13.0
│   │   │   │       └── libc v0.2.71
│   │   │   ├── futures-io v0.3.5
│   │   │   ├── futures-sink v0.3.5
│   │   │   ├── futures-task v0.3.5 (*)
│   │   │   └── futures-util v0.3.5 (*)
│   │   ├── log v0.4.8
│   │   │   └── cfg-if v0.1.10
│   │   └── tokio v0.2.21
│   │       ├── bytes v0.5.5
│   │       ├── futures-core v0.3.5
│   │       ├── num_cpus v1.13.0 (*)
│   │       ├── pin-project-lite v0.1.7
│   │       └── slab v0.4.2
│   ├── iced_wgpu v0.2.2 (/Users/dev/Projects/xia/modules/iced/wgpu)
│   │   ├── bytemuck v1.2.0
│   │   ├── gfx-memory v0.1.1
│   │   │   ├── fxhash v0.2.1
│   │   │   │   └── byteorder v1.3.4
│   │   │   ├── gfx-hal v0.5.2
│   │   │   │   ├── bitflags v1.2.1
│   │   │   │   └── raw-window-handle v0.3.3
│   │   │   │       └── libc v0.2.71
│   │   │   ├── hibitset v0.6.3
│   │   │   │   └── atom v0.3.5
│   │   │   ├── log v0.4.8 (*)
│   │   │   └── slab v0.4.2
│   │   ├── glam v0.8.7
│   │   ├── glyph_brush v0.7.0
│   │   │   ├── glyph_brush_draw_cache v0.1.0
│   │   │   │   ├── ab_glyph v0.2.2
│   │   │   │   │   ├── ab_glyph_rasterizer v0.1.2
│   │   │   │   │   └── owned_ttf_parser v0.6.0
│   │   │   │   │       └── ttf-parser v0.6.1
│   │   │   │   ├── crossbeam-channel v0.4.2
│   │   │   │   │   ├── crossbeam-utils v0.7.2
│   │   │   │   │   │   ├── cfg-if v0.1.10
│   │   │   │   │   │   └── lazy_static v1.4.0
│   │   │   │   │   │   [build-dependencies]
│   │   │   │   │   │   └── autocfg v1.0.0
│   │   │   │   │   └── maybe-uninit v2.0.0
│   │   │   │   ├── crossbeam-deque v0.7.3
│   │   │   │   │   ├── crossbeam-epoch v0.8.2
│   │   │   │   │   │   ├── cfg-if v0.1.10
│   │   │   │   │   │   ├── crossbeam-utils v0.7.2 (*)
│   │   │   │   │   │   ├── lazy_static v1.4.0
│   │   │   │   │   │   ├── maybe-uninit v2.0.0
│   │   │   │   │   │   ├── memoffset v0.5.4
│   │   │   │   │   │   │   [build-dependencies]
│   │   │   │   │   │   │   └── autocfg v1.0.0
│   │   │   │   │   │   └── scopeguard v1.1.0
│   │   │   │   │   │   [build-dependencies]
│   │   │   │   │   │   └── autocfg v1.0.0
│   │   │   │   │   ├── crossbeam-utils v0.7.2 (*)
│   │   │   │   │   └── maybe-uninit v2.0.0
│   │   │   │   ├── linked-hash-map v0.5.3
│   │   │   │   ├── rayon v1.3.1
│   │   │   │   │   ├── crossbeam-deque v0.7.3 (*)
│   │   │   │   │   ├── either v1.5.3
│   │   │   │   │   └── rayon-core v1.7.1
│   │   │   │   │       ├── crossbeam-deque v0.7.3 (*)
│   │   │   │   │       ├── crossbeam-queue v0.2.3
│   │   │   │   │       │   ├── cfg-if v0.1.10
│   │   │   │   │       │   ├── crossbeam-utils v0.7.2 (*)
│   │   │   │   │       │   └── maybe-uninit v2.0.0
│   │   │   │   │       ├── crossbeam-utils v0.7.2 (*)
│   │   │   │   │       ├── lazy_static v1.4.0
│   │   │   │   │       └── num_cpus v1.13.0 (*)
│   │   │   │   │   [build-dependencies]
│   │   │   │   │   └── autocfg v1.0.0
│   │   │   │   └── rustc-hash v1.1.0
│   │   │   ├── glyph_brush_layout v0.2.0
│   │   │   │   ├── ab_glyph v0.2.2 (*)
│   │   │   │   ├── approx v0.3.2
│   │   │   │   │   └── num-traits v0.2.12
│   │   │   │   │       [build-dependencies]
│   │   │   │   │       └── autocfg v1.0.0
│   │   │   │   └── xi-unicode v0.2.1
│   │   │   ├── log v0.4.8 (*)
│   │   │   ├── ordered-float v1.0.2
│   │   │   │   └── num-traits v0.2.12 (*)
│   │   │   ├── rustc-hash v1.1.0
│   │   │   └── twox-hash v1.5.0
│   │   │       └── rand v0.7.3
│   │   │           ├── getrandom v0.1.14
│   │   │           │   ├── cfg-if v0.1.10
│   │   │           │   └── libc v0.2.71
│   │   │           ├── libc v0.2.71
│   │   │           ├── rand_chacha v0.2.2
│   │   │           │   ├── ppv-lite86 v0.2.8
│   │   │           │   └── rand_core v0.5.1
│   │   │           │       └── getrandom v0.1.14 (*)
│   │   │           └── rand_core v0.5.1 (*)
│   │   ├── guillotiere v0.5.2
│   │   │   ├── euclid v0.20.13
│   │   │   │   └── num-traits v0.2.12 (*)
│   │   │   └── svg_fmt v0.4.1
│   │   ├── iced_graphics v0.1.0 (/Users/dev/Projects/xia/modules/iced/graphics)
│   │   │   ├── bytemuck v1.2.0
│   │   │   ├── font-kit v0.6.0
│   │   │   │   ├── bitflags v1.2.1
│   │   │   │   ├── byteorder v1.3.4
│   │   │   │   ├── core-foundation v0.7.0
│   │   │   │   │   ├── core-foundation-sys v0.7.0
│   │   │   │   │   └── libc v0.2.71
│   │   │   │   ├── core-graphics v0.19.0
│   │   │   │   │   ├── bitflags v1.2.1
│   │   │   │   │   ├── core-foundation v0.7.0 (*)
│   │   │   │   │   ├── foreign-types v0.3.2
│   │   │   │   │   │   └── foreign-types-shared v0.1.1
│   │   │   │   │   └── libc v0.2.71
│   │   │   │   ├── core-text v15.0.0
│   │   │   │   │   ├── core-foundation v0.7.0 (*)
│   │   │   │   │   ├── core-graphics v0.19.0 (*)
│   │   │   │   │   ├── foreign-types v0.3.2 (*)
│   │   │   │   │   └── libc v0.2.71
│   │   │   │   ├── dirs v2.0.2
│   │   │   │   │   ├── cfg-if v0.1.10
│   │   │   │   │   └── dirs-sys v0.3.5
│   │   │   │   │       └── libc v0.2.71
│   │   │   │   ├── float-ord v0.2.0
│   │   │   │   ├── lazy_static v1.4.0
│   │   │   │   ├── libc v0.2.71
│   │   │   │   ├── log v0.4.8 (*)
│   │   │   │   ├── pathfinder_geometry v0.5.1
│   │   │   │   │   ├── log v0.4.8 (*)
│   │   │   │   │   └── pathfinder_simd v0.5.0
│   │   │   │   │       [build-dependencies]
│   │   │   │   │       └── rustc_version v0.2.3
│   │   │   │   │           └── semver v0.9.0
│   │   │   │   │               └── semver-parser v0.7.0
│   │   │   │   ├── pathfinder_simd v0.5.0 (*)
│   │   │   │   └── walkdir v2.3.1
│   │   │   │       └── same-file v1.0.6
│   │   │   ├── glam v0.8.7
│   │   │   ├── iced_native v0.2.2 (/Users/dev/Projects/xia/modules/iced/native)
│   │   │   │   ├── iced_core v0.2.1 (/Users/dev/Projects/xia/modules/iced/core)
│   │   │   │   ├── iced_futures v0.1.2 (/Users/dev/Projects/xia/modules/iced/futures) (*)
│   │   │   │   ├── num-traits v0.2.12 (*)
│   │   │   │   ├── twox-hash v1.5.0 (*)
│   │   │   │   └── unicode-segmentation v1.6.0
│   │   │   ├── iced_style v0.1.0 (/Users/dev/Projects/xia/modules/iced/style)
│   │   │   │   └── iced_core v0.2.1 (/Users/dev/Projects/xia/modules/iced/core)
│   │   │   ├── lyon v0.15.8
│   │   │   │   ├── lyon_algorithms v0.15.0
│   │   │   │   │   ├── lyon_path v0.15.2
│   │   │   │   │   │   └── lyon_geom v0.15.3
│   │   │   │   │   │       ├── arrayvec v0.5.1
│   │   │   │   │   │       ├── euclid v0.20.13 (*)
│   │   │   │   │   │       └── num-traits v0.2.12 (*)
│   │   │   │   │   └── sid v0.6.1
│   │   │   │   │       └── num-traits v0.2.12 (*)
│   │   │   │   └── lyon_tessellation v0.15.8
│   │   │   │       ├── arrayvec v0.5.1
│   │   │   │       ├── lyon_path v0.15.2 (*)
│   │   │   │       └── sid v0.6.1 (*)
│   │   │   └── raw-window-handle v0.3.3 (*)
│   │   ├── iced_native v0.2.2 (/Users/dev/Projects/xia/modules/iced/native) (*)
│   │   ├── log v0.4.8 (*)
│   │   ├── raw-window-handle v0.3.3 (*)
│   │   ├── wgpu v0.5.0
│   │   │   ├── arrayvec v0.5.1
│   │   │   ├── parking_lot v0.10.2
│   │   │   │   ├── lock_api v0.3.4
│   │   │   │   │   └── scopeguard v1.1.0
│   │   │   │   └── parking_lot_core v0.7.2
│   │   │   │       ├── cfg-if v0.1.10
│   │   │   │       ├── libc v0.2.71
│   │   │   │       └── smallvec v1.4.0
│   │   │   ├── raw-window-handle v0.3.3 (*)
│   │   │   ├── smallvec v1.4.0
│   │   │   ├── wgpu-core v0.5.5
│   │   │   │   ├── arrayvec v0.5.1
│   │   │   │   ├── bitflags v1.2.1
│   │   │   │   ├── copyless v0.1.5
│   │   │   │   ├── fxhash v0.2.1 (*)
│   │   │   │   ├── gfx-backend-empty v0.5.0
│   │   │   │   │   ├── gfx-hal v0.5.2 (*)
│   │   │   │   │   └── raw-window-handle v0.3.3 (*)
│   │   │   │   ├── gfx-backend-metal v0.5.4
│   │   │   │   │   ├── arrayvec v0.5.1
│   │   │   │   │   ├── bitflags v1.2.1
│   │   │   │   │   ├── block v0.1.6
│   │   │   │   │   ├── cocoa v0.20.1
│   │   │   │   │   │   ├── bitflags v1.2.1
│   │   │   │   │   │   ├── block v0.1.6
│   │   │   │   │   │   ├── core-foundation v0.7.0 (*)
│   │   │   │   │   │   ├── core-graphics v0.19.0 (*)
│   │   │   │   │   │   ├── foreign-types v0.3.2 (*)
│   │   │   │   │   │   ├── libc v0.2.71
│   │   │   │   │   │   └── objc v0.2.7
│   │   │   │   │   │       ├── malloc_buf v0.0.6
│   │   │   │   │   │       │   └── libc v0.2.71
│   │   │   │   │   │       └── objc_exception v0.1.2
│   │   │   │   │   │           [build-dependencies]
│   │   │   │   │   │           └── cc v1.0.54
│   │   │   │   │   ├── copyless v0.1.5
│   │   │   │   │   ├── core-graphics v0.19.0 (*)
│   │   │   │   │   ├── foreign-types v0.3.2 (*)
│   │   │   │   │   ├── gfx-auxil v0.4.0
│   │   │   │   │   │   ├── fxhash v0.2.1 (*)
│   │   │   │   │   │   ├── gfx-hal v0.5.2 (*)
│   │   │   │   │   │   └── spirv_cross v0.20.0
│   │   │   │   │   │       [build-dependencies]
│   │   │   │   │   │       └── cc v1.0.54
│   │   │   │   │   ├── gfx-hal v0.5.2 (*)
│   │   │   │   │   ├── lazy_static v1.4.0
│   │   │   │   │   ├── log v0.4.8 (*)
│   │   │   │   │   ├── metal v0.18.0
│   │   │   │   │   │   ├── bitflags v1.2.1
│   │   │   │   │   │   ├── block v0.1.6
│   │   │   │   │   │   ├── cocoa v0.20.1 (*)
│   │   │   │   │   │   ├── core-graphics v0.19.0 (*)
│   │   │   │   │   │   ├── foreign-types v0.3.2 (*)
│   │   │   │   │   │   ├── log v0.4.8 (*)
│   │   │   │   │   │   └── objc v0.2.7 (*)
│   │   │   │   │   ├── objc v0.2.7 (*)
│   │   │   │   │   ├── parking_lot v0.10.2 (*)
│   │   │   │   │   ├── range-alloc v0.1.1
│   │   │   │   │   ├── raw-window-handle v0.3.3 (*)
│   │   │   │   │   ├── smallvec v1.4.0
│   │   │   │   │   ├── spirv_cross v0.20.0 (*)
│   │   │   │   │   └── storage-map v0.2.0
│   │   │   │   │       └── lock_api v0.3.4 (*)
│   │   │   │   ├── gfx-descriptor v0.1.0
│   │   │   │   │   ├── fxhash v0.2.1 (*)
│   │   │   │   │   ├── gfx-hal v0.5.2 (*)
│   │   │   │   │   └── log v0.4.8 (*)
│   │   │   │   ├── gfx-hal v0.5.2 (*)
│   │   │   │   ├── gfx-memory v0.1.1 (*)
│   │   │   │   ├── log v0.4.8 (*)
│   │   │   │   ├── parking_lot v0.10.2 (*)
│   │   │   │   ├── peek-poke v0.2.0
│   │   │   │   │   └── peek-poke-derive v0.2.1
│   │   │   │   │       ├── proc-macro2 v1.0.18 (*)
│   │   │   │   │       ├── quote v1.0.7 (*)
│   │   │   │   │       ├── syn v1.0.31 (*)
│   │   │   │   │       ├── synstructure v0.12.4
│   │   │   │   │       │   ├── proc-macro2 v1.0.18 (*)
│   │   │   │   │       │   ├── quote v1.0.7 (*)
│   │   │   │   │       │   ├── syn v1.0.31 (*)
│   │   │   │   │       │   └── unicode-xid v0.2.0
│   │   │   │   │       └── unicode-xid v0.2.0
│   │   │   │   ├── smallvec v1.4.0
│   │   │   │   ├── vec_map v0.8.2
│   │   │   │   └── wgpu-types v0.5.1
│   │   │   │       ├── bitflags v1.2.1
│   │   │   │       └── peek-poke v0.2.0 (*)
│   │   │   ├── wgpu-native v0.5.0
│   │   │   │   ├── arrayvec v0.5.1
│   │   │   │   ├── lazy_static v1.4.0
│   │   │   │   ├── libc v0.2.71
│   │   │   │   ├── objc v0.2.7 (*)
│   │   │   │   ├── parking_lot v0.10.2 (*)
│   │   │   │   ├── raw-window-handle v0.3.3 (*)
│   │   │   │   ├── wgpu-core v0.5.5 (*)
│   │   │   │   └── wgpu-types v0.5.1 (*)
│   │   │   └── wgpu-types v0.5.1 (*)
│   │   ├── wgpu_glyph v0.9.0
│   │   │   ├── glyph_brush v0.7.0 (*)
│   │   │   ├── log v0.4.8 (*)
│   │   │   ├── wgpu v0.5.0 (*)
│   │   │   └── zerocopy v0.3.0
│   │   │       ├── byteorder v1.3.4
│   │   │       └── zerocopy-derive v0.2.0
│   │   │           ├── proc-macro2 v1.0.18 (*)
│   │   │           ├── syn v1.0.31 (*)
│   │   │           └── synstructure v0.12.4 (*)
│   │   └── zerocopy v0.3.0 (*)
│   └── iced_winit v0.1.1 (/Users/dev/Projects/xia/modules/iced/winit)
│       ├── iced_graphics v0.1.0 (/Users/dev/Projects/xia/modules/iced/graphics) (*)
│       ├── iced_native v0.2.2 (/Users/dev/Projects/xia/modules/iced/native) (*)
│       ├── log v0.4.8 (*)
│       ├── window_clipboard v0.1.1
│       │   ├── clipboard_macos v0.1.0
│       │   │   ├── objc v0.2.7 (*)
│       │   │   ├── objc-foundation v0.1.1
│       │   │   │   ├── block v0.1.6
│       │   │   │   ├── objc v0.2.7 (*)
│       │   │   │   └── objc_id v0.1.1
│       │   │   │       └── objc v0.2.7 (*)
│       │   │   └── objc_id v0.1.1 (*)
│       │   └── raw-window-handle v0.3.3 (*)
│       └── winit v0.22.2
│           ├── bitflags v1.2.1
│           ├── cocoa v0.20.1 (*)
│           ├── core-foundation v0.7.0 (*)
│           ├── core-graphics v0.19.0 (*)
│           ├── core-video-sys v0.1.4
│           │   ├── cfg-if v0.1.10
│           │   ├── core-foundation-sys v0.7.0
│           │   ├── core-graphics v0.19.0 (*)
│           │   ├── libc v0.2.71
│           │   └── objc v0.2.7 (*)
│           ├── dispatch v0.2.0
│           ├── instant v0.1.4
│           ├── lazy_static v1.4.0
│           ├── libc v0.2.71
│           ├── log v0.4.8 (*)
│           ├── objc v0.2.7 (*)
│           └── raw-window-handle v0.3.3 (*)
├── itertools v0.9.0
│   └── either v1.5.3
├── rustc-hash v1.1.0
└── tokio v0.2.21 (*)
```
</details>

_Originally posted by @declanvk in https://github.com/hecrj/iced/issues/342#issuecomment-649230420_

This is a duplicate of the earlier issue, but I didn't think that it would get much visibility as a comment on a closed issue.

**Comment by hecrj** [comment]
I closed the original issue because I believe this is most likely a driver problem related to the `wgpu` backends:

- What's your graphics adapter?
- Do you have an integrated GPU?
- Are all your graphics drivers up-to-date?

Finally, does it work if you use the OpenGL renderer?

```
cargo run --package game_of_life --features glow,glow_canvas
```

**Comment by declanvk** [comment]
- Running with the OpenGL renderer failed:
```
     Running `target/debug/game_of_life`
thread 'main' panicked at 'gl function was not loaded', /Users/dev/Projects/xia/modules/iced/target/debug/build/glow-2e5068f6d6a2ecbe/out/opengl_bindings.rs:1527:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
which seems to relate to an existing gfx issue: https://github.com/gfx-rs/gfx/issues/1298

- I think my drivers are up to date, but its possible that I would need to update to the latest mac OS (Catalina?).
- The information on my graphics card (I think it is integrated) and displays (likely not relevant):

```
Intel Iris Graphics 6100:

  Chipset Model:	Intel Iris Graphics 6100
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x162b
  Revision ID:	0x0009
  Metal:	Supported, feature set macOS GPUFamily1 v4
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2560 x 1600 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
```

Let me know if there's any other info I can provide, or if I should file this issue directly with `wgpu`.

**Comment by hecrj** [comment]
@declanvk It would be helpful if you could provide a full backtrace of that error.

**Comment by declanvk** [comment]
Here is the full backtrace:
```
13:07 $ RUST_BACKTRACE=full cargo run -p game_of_life --features glow,glow_canvas
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/game_of_life`
thread 'main' panicked at 'gl function was not loaded', /Users/dev/Projects/xia/modules/iced/target/debug/build/glow-2e5068f6d6a2ecbe/out/opengl_bindings.rs:1527:13
stack backtrace:
   0:        0x11008966f - backtrace::backtrace::libunwind::trace::hdff08984d375d02a
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:        0x11008966f - backtrace::backtrace::trace_unsynchronized::h1a393bcdfc10be62
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:        0x11008966f - std::sys_common::backtrace::_print_fmt::h063c5f96b3f1deaf
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x11008966f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ad47541fb823094
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x1100ab2ae - core::fmt::write::he23e9bd6497f06c3
                               at src/libcore/fmt/mod.rs:1069
   5:        0x110087347 - std::io::Write::write_fmt::h91528f1131e6004e
                               at src/libstd/io/mod.rs:1504
   6:        0x11008b6da - std::sys_common::backtrace::_print::ha16b452b57f4cc4c
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x11008b6da - std::sys_common::backtrace::print::hdcfe7b1cd849140e
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x11008b6da - std::panicking::default_hook::{{closure}}::h1983f014a45a477e
                               at src/libstd/panicking.rs:198
   9:        0x11008b41c - std::panicking::default_hook::hb0d9b93b5be8b120
                               at src/libstd/panicking.rs:218
  10:        0x11008bd88 - std::panicking::rust_panic_with_hook::h9f3faafe0983de5c
                               at src/libstd/panicking.rs:511
  11:        0x10feb62f6 - std::panicking::begin_panic::hc7d51155fef976c9
                               at /Users/dev/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:438
  12:        0x10feaebec - glow::native::native_gl::missing_fn_panic::h7fcd09735d417846
                               at /Users/dev/Projects/xia/modules/iced/target/debug/build/glow-2e5068f6d6a2ecbe/out/opengl_bindings.rs:1527
  13:        0x10fe0dcfc - glow::native::native_gl::Gl::ObjectLabel::hf3e119e3d721d9db
                               at /Users/dev/Projects/xia/modules/iced/target/debug/build/glow-2e5068f6d6a2ecbe/out/opengl_bindings.rs:4107
  14:        0x10fe0e029 - <glow::native::Context as glow::HasContext>::object_label::h1438d339ca0b7979
                               at /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.4.0/src/native.rs:1775
  15:        0x10fe0ef8a - glow_glyph::pipeline::cache::Cache::new::h7a19218a8da7ac2a
                               at /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/glow_glyph-0.2.0/src/pipeline/cache.rs:18
  16:        0x10fe0c3e0 - glow_glyph::pipeline::Pipeline::new::h54b9a2c388a4d98e
                               at /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/glow_glyph-0.2.0/src/pipeline.rs:26
  17:        0x10fd495b9 - glow_glyph::GlyphBrush<F,H>::new::h24975b92213ca8e8
                               at /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/glow_glyph-0.2.0/src/lib.rs:269
  18:        0x10fe0bed8 - glow_glyph::builder::GlyphBrushBuilder<F,H>::build::hd3ae84793bcf1aa7
                               at /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/glow_glyph-0.2.0/src/builder.rs:73
  19:        0x10fd74fcd - iced_glow::text::Pipeline::new::h1861b993c8a64f66
                               at glow/src/text.rs:42
  20:        0x10fd480da - iced_glow::backend::Backend::new::he875913e3f619499
                               at glow/src/backend.rs:29
  21:        0x10fccb78c - <iced_glow::window::compositor::Compositor as iced_graphics::window::gl_compositor::GLCompositor>::new::h5e9a220635b9ee15
                               at /Users/dev/Projects/xia/modules/iced/glow/src/window/compositor.rs:34
  22:        0x10fd20e3f - iced_glutin::application::run::h3bcc08bfa38e427b
                               at /Users/dev/Projects/xia/modules/iced/glutin/src/application.rs:86
  23:        0x10fd34554 - iced::application::Application::run::hfc05484f3341977a
                               at /Users/dev/Projects/xia/modules/iced/src/application.rs:229
  24:        0x10fca02f4 - game_of_life::main::h64d8b4fab3851529
                               at examples/game_of_life/src/main.rs:16
  25:        0x10fd1e65e - std::rt::lang_start::{{closure}}::h14f043b75b9db9c6
                               at /Users/dev/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  26:        0x11008c1b9 - std::rt::lang_start_internal::{{closure}}::hcd3fdb11e5e01a21
                               at src/libstd/rt.rs:52
  27:        0x11008c1b9 - std::panicking::try::do_call::hd8e8ada4e26d8788
                               at src/libstd/panicking.rs:331
  28:        0x11008c1b9 - std::panicking::try::hf951a93b7ea92f92
                               at src/libstd/panicking.rs:274
  29:        0x11008c1b9 - std::panic::catch_unwind::he82f6de4bcfc0f8c
                               at src/libstd/panic.rs:394
  30:        0x11008c1b9 - std::rt::lang_start_internal::h795af50241e12334
                               at src/libstd/rt.rs:51
  31:        0x10fd1e641 - std::rt::lang_start::h58913e5aa948f7c7
                               at /Users/dev/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  32:        0x10fca1bd2 - main
```

**Comment by hecrj** [comment]
@declanvk Interesting! It seems to be panicking when [setting an object label in `glow_glyph`](https://github.com/hecrj/glow_glyph/blob/3f16838d6d4c94cfe58cdcd70321e64bfc3941c4/src/pipeline/cache.rs#L18).

This may not be supported by your version of OpenGL. What happens if you run it in `--release` mode?

**Comment by declanvk** [comment]
I checked my OpenGL version, and it shows as:
```bash
13:18 $ glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 INTEL-12.10.19
```

Running with the `--release` flag worked and displayed the grid correctly:

<img width="960" alt="Screen Shot 2020-06-26 at 1 22 48 PM" src="https://user-images.githubusercontent.com/7276122/85897969-3fc19600-b7b0-11ea-8fdd-c6dc39fc09eb.png">

**Comment by hecrj** [comment]
@declanvk Great! I'll remove the `object_label` from `glow_glyph` and release a new patch version with the fix. Thank you for testing this!

About the original issue, it's hard for me to debug it without being able to reproduce it. Hopefully the root of the problem becomes more apparent as we get more bug reports and `wgpu` evolves.
