### ISSUE TITLE
Unable to run basic hello world on Linux

### ISSUE THREAD

**Issue by crone123** [iced-rs/iced#613]
Hello,
I am trying to test this library, because it seems to be really nice, but I can't run even the most basic example on my desktop.
Kubuntu 20.04 LTS, with Nvidia Drivers 450.80 on Nvidia GTX 1050.

I tried this example:
```
use iced::{Element, Sandbox, Settings, Text};
struct Hello;

impl Sandbox for Hello {
    type Message = ();

    fn new() -> Hello {
        Hello
    }

    fn title(&self) -> String {
        String::from("A cool application")
    }

    fn update(&mut self, _message: Self::Message) {
        // This application has no interactions
    }

    fn view(&mut self) -> Element<Self::Message> {
        Text::new("Hello, world!").into()
    }
}

fn main() {
    Hello::run(Settings::default())
}
```

(Sandbox or Application doesn't make any differences, I get the same problem)

And I get this error while running:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:266:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Full backtrace:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:266:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:483:5
   1: std::panicking::begin_panic_fmt
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:437:5
   2: <wgpu_native::hub::Storage<T,I> as core::ops::index::Index<I>>::index
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/hub.rs:120:9
   3: wgpu_native::command::command_encoder_begin_render_pass::{{closure}}
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:266:23
   4: core::option::Option<T>::map
             at /home/valentin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:453:29
   5: wgpu_native::command::command_encoder_begin_render_pass
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:264:28
   6: wgpu_command_encoder_begin_render_pass
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:739:5
   7: wgpu::CommandEncoder::begin_render_pass
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1059:17
   8: <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::draw
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.3/src/window/backend.rs:81:17
   9: iced_winit::application::Application::run::{{closure}}
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.rs:331:40
  10: winit::platform_impl::platform::sticky_exit_callback
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698:5
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:312:21
  12: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:390:9
  13: winit::platform_impl::platform::EventLoop<T>::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:645:35
  14: winit::event_loop::EventLoop<T>::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149:9
  15: iced_winit::application::Application::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.rs:214:9
  16: iced::application::Application::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.1/src/application.rs:201:13
  17: iced::sandbox::Sandbox::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.1/src/sandbox.rs:139:9
  18: iced_app::main
             at ./src/main.rs:80:5
  19: core::ops::function::FnOnce::call_once
             at /home/valentin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Can you help me?
Thank you :)

**Comment by manokara** [comment]
Do you have Vulkan drivers installed? iced with the default `wgpu` only works with Vulkan. Also, you're using the crates.io version, which is very outdated. Try one of the examples in the repo with `cargo run --package example_name` to use the latest code.

You could also build with the `glow` feature to use OpenGL instead of Vulkan: `cargo run --features glow --package example_name`, however the `glow` version isn't as feature complete as `wgpu`, so some things may look weird.

**Comment by crone123** [comment]
Ok, in the crates.io version, the feature "glow" doesn't exists.
Hum, the latest release on this repository is the same commit as on crates.io, should I just use the latest master commit?

I tired to compile with this:
```
iced = {git = "https://github.com/hecrj/iced.git", commit = "wgpu-0.2.3"}
```

And I got this problem:
```
thread 'main' panicked at 'Next frame: Timeout', /home/valentin/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/73811c3/wgpu/src/window/compositor.rs:130:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Full backtrace:
```
thread 'main' panicked at 'Next frame: Timeout', /home/valentin/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/73811c3/wgpu/src/window/compositor.rs:130:52
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:483:5
   1: core::panicking::panic_fmt
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/panicking.rs:85:14
   2: core::option::expect_none_failed
             at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::expect
             at /home/valentin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933:23
   4: <iced_wgpu::window::compositor::Compositor as iced_graphics::window::compositor::Compositor>::draw
             at /home/valentin/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/73811c3/wgpu/src/window/compositor.rs:130:21
   5: iced_winit::application::run_instance::{{closure}}
             at /home/valentin/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/73811c3/winit/src/application.rs:331:45
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/valentin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   7: iced_winit::application::run::{{closure}}
             at /home/valentin/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/73811c3/winit/src/application.rs:191:24
   8: winit::platform_impl::platform::sticky_exit_callback
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:726:5
   9: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:308:21
  10: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:386:9
  11: winit::platform_impl::platform::EventLoop<T>::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:642:56
  12: winit::event_loop::EventLoop<T>::run
             at /home/valentin/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/event_loop.rs:154:9
  13: iced_winit::application::run
             at /home/valentin/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/73811c3/winit/src/application.rs:181:5
  14: iced::application::Application::run
             at /home/valentin/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/73811c3/src/application.rs:229:16
  15: iced::sandbox::Sandbox::run
             at /home/valentin/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/73811c3/src/sandbox.rs:166:9
  16: iced_app::main
             at ./src/main.rs:80:5
  17: core::ops::function::FnOnce::call_once
             at /home/valentin/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```


And ok, with this I am able to compile:
```
iced = {git = "https://github.com/hecrj/iced.git", commit = "wgpu-0.2.3", features= ["glow"]}
```
and it runs :)

Why did you not add the glow feature by default, or as fallback by default if vulkan doesn't work? (Something like this, to prevent crash..especially if you develop a small app on a platform where it works, and you send it to a user where it doesn't work...)
I don't know if my drivers support vulkan, but what I know is vulkan is not currently supported by all platforms... or in beta, so a fallback renderer, maybe a software renderer is good...
glow is opengl or software renderer?

Thank you :)

**Comment by manokara** [comment]
> Hum, the latest release on this repository is the same commit as on crates.io, should I just use the latest master commit?

Yes, by latest release I meant master. Why are you using the `wgpu-0.2.3` tag? That commit is indeed as old as the crates.io version.

> Why did you not add the glow feature by default, or as fallback by default if vulkan doesn't work?

Well, one day wgpu will also support OpenGL so we'll only need one graphics library. I think glow fallback would be possible, but I'm not sure how feasible that is given that glow is not as mature as wgpu as I mentioned before, and maybe there's Rust shenanigans involved. I'm not a project mantainer, by the way. I know there has been some discussion around that but can't remember how it turned out.

> glow is opengl or software renderer?

It's OpenGL. There's a software renderer in the works, but it's on someone else's repo and I think it'll be a while until it is done.

Happy coding :)

**Comment by kaimast** [comment]
Do you have only the Nvidia GPU? 

I remember having some issues with Prime and Vulkan a while ago using wgpu.

**Comment by crone123** [comment]
Hello,
I have a laptop with intel/nvidia cards.
I have now the 470 driver, I will test again when I have some time...

**Comment by hecrj** [comment]
Closing as the issue seems stale. Feel free to repoen if you end up testing again!
